Repository hash-org/hashc, pull requests merged in 2022-01, with the labels that each got.

#97 Add link to the Hash book in the lang README
  README.md
Labels: documentation

#102 fix: use `Debug` formatter for converting the `OperatorKind` instead of `Display`
  compiler/hash-ast/src/operator.rs
  compiler/hash-parser/src/operator.rs
Labels: bug, parser

#106 Typechecking: A first attempt at trait resolution
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/ident.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/state.rs
  compiler/hash-typecheck/src/storage.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-utils/src/lib.rs
Labels: typechecking

#111 Pipeline: A new way of compiler bootstrapping
  Cargo.lock
  Cargo.toml
  compiler/hash-ast/Cargo.toml
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/error.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-ast/src/module.rs
  compiler/hash-ast/src/parse.rs
  compiler/hash-ast/src/resolve.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/backend.rs
  compiler/hash-parser/src/error.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-parser/src/lexer.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/operator.rs
  compiler/hash-parser/src/parser.rs
  compiler/hash-parser/src/token.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-reporting/src/reporting.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/lib.rs
  compiler/hash-source/src/location.rs
  compiler/hash-source/src/module.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/state.rs
  compiler/hash-typecheck/src/storage.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/main.rs
  tests/parser/Cargo.toml
  tests/parser/benches/benches.rs
  tests/parser/tests/test_runner.rs
Labels: organisation, core

#116 Typecheck: Implement enums
  Cargo.lock
  Cargo.toml
  compiler/hash-ast/src/tree.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-interactive/src/lib.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
Labels: typechecking

#117 Typechecking: Minimum traits
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
Labels: typechecking

#118 Typechecker: Implement tuple types
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-reporting/src/reporting.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-utils/src/tree_writing.rs
Labels: error-reporting, typechecking

#122 AST: use special variant for function types.
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
Labels: typechecking

#126 Typecheck: Implement patterns and match blocks
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-parser/src/error.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-reporting/src/reporting.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
Labels: error-reporting, typechecking
