Repository hash-org/hashc, pull requests merged in 2022-08, with the labels that each got.

#435 TC: Restructure members and core defs
  compiler/hash-source/src/identifier.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/mod.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/cache.rs
  compiler/hash-typecheck/src/ops/core.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/params.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
Labels: typechecking

#447 TC: Implement generic stores with interior mutability
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/store.rs
Labels: typechecking, alloc

#436 TC: Implement exhaustiveness and usefulness checking
  Cargo.lock
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/Cargo.toml
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/fields.rs
  compiler/hash-typecheck/src/exhaustiveness/list.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/matrix.rs
  compiler/hash-typecheck/src/exhaustiveness/mod.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/stack.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/exhaustiveness.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/storage/constructors.rs
  compiler/hash-typecheck/src/storage/deconstructed_pat.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/pats.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking, pattern-matching

#451 Parser fixes
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-lexer/src/error.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-token/Cargo.toml
  compiler/hash-token/src/lib.rs
  tests/parser/tests/cases/should_fail/char_literals/case.stderr
  tests/parser/tests/cases/should_fail/dangling_paren_tree/case.stderr
  tests/parser/tests/cases/should_fail/dangling_parenthesis/case.stderr
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.stderr
  tests/parser/tests/cases/should_fail/double_comma_in_function_call/case.stderr
  tests/parser/tests/cases/should_fail/double_comma_in_list_literal/case.stderr
  tests/parser/tests/cases/should_fail/double_hash/case.stderr
  tests/parser/tests/cases/should_fail/empty_type_args/case.stderr
  tests/parser/tests/cases/should_fail/expresionless_directive/case.stderr
  tests/parser/tests/cases/should_fail/goodbye_world/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_list_pattern/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_spread_pattern/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_name_assignment/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_type_annotation/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_type/case.stderr
  tests/parser/tests/cases/should_fail/integer_literal_too_large/case.stderr
  tests/parser/tests/cases/should_fail/invalid_float_exponent/case.stderr
  tests/parser/tests/cases/should_fail/invalid_unicode_char/case.stderr
  tests/parser/tests/cases/should_fail/issue_223/case.stderr
  tests/parser/tests/cases/should_fail/issue_449/case.hash
  tests/parser/tests/cases/should_fail/issue_449/case.stderr
  tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_literal_arrow/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_type/case.stderr
  tests/parser/tests/cases/should_fail/malformed_list_literal/case.stderr
  tests/parser/tests/cases/should_fail/missing_comma_in_struct_field/case.stderr
  tests/parser/tests/cases/should_fail/missing_default_value_in_function_literal/case.stderr
  tests/parser/tests/cases/should_fail/missing_expression_in_function_call/case.stderr
  tests/parser/tests/cases/should_fail/missing_raw_ref_type/case.stderr
  tests/parser/tests/cases/should_fail/missing_ref_type/case.stderr
  tests/parser/tests/cases/should_fail/missing_type_in_function_literal/case.stderr
  tests/parser/tests/cases/should_fail/multi_code_point_char_literal/case.stderr
  tests/parser/tests/cases/should_fail/non_existant_import/case.stderr
  tests/parser/tests/cases/should_fail/non_hex_ascii_escape_code/case.stderr
  tests/parser/tests/cases/should_fail/non_hex_unicode_char/case.stderr
  tests/parser/tests/cases/should_fail/pat_match_missing_semi/case.stderr
  tests/parser/tests/cases/should_fail/short_ascii_code/case.stderr
  tests/parser/tests/cases/should_fail/spread_pattern_in_namespace_pattern/case.stderr
  tests/parser/tests/cases/should_fail/triple_colon_in_access_name/case.stderr
  tests/parser/tests/cases/should_fail/unclose_type_args/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_char_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_set_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_string_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_unicode_literal/case.stderr
  tests/parser/tests/cases/should_fail/unknown_escape_sequence/case.stderr
  tests/parser/tests/cases/should_pass/negative_numerics_in_pats/case.hash
Labels: bug, parser

#452 lang: add support for range pats
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/parser/tests/cases/should_fail/incomplere_exclusive_range_pat/case.hash
  tests/parser/tests/cases/should_fail/incomplere_exclusive_range_pat/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_range_pat/case.hash
  tests/parser/tests/cases/should_fail/incomplete_range_pat/case.stderr
  tests/parser/tests/cases/should_fail/malformed_range_pat/case.hash
  tests/parser/tests/cases/should_fail/malformed_range_pat/case.stderr
  tests/parser/tests/cases/should_pass/range_pats/case.hash
Labels: language

#453 docs: fix broken links and private item warnings
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/diagnostics/origins.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-utils/src/store.rs
Labels: documentation

#457 BugFix: Fix problem where types are not runtime instantiable
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-utils/src/store.rs
Labels: bug, typechecking

#458 TC: fix exhaustiveness issues
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/matrix.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/stack.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/fmt.rs
Labels: typechecking, pattern-matching

#459 reporting: Introduce `Diagnostics` trait and intergrate the `Lexer` as a proof of concept
  Cargo.lock
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-lexer/Cargo.toml
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/diagnostics/mod.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-reporting/src/diagnostic.rs
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-utils/src/store.rs
  tests/parser/benches/benches.rs
  tests/parser/tests/cases/should_fail/multi_error_char/case.hash
  tests/parser/tests/cases/should_fail/multi_error_char/case.stderr
  tests/parser/tests/cases/should_fail/non_existant_import/case.stderr
  tests/parser/tests/cases/should_fail/non_hex_unicode_char/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_unicode_literal/case.stderr
  tests/parser/tests/cases/should_fail/unknown_escape_sequence/case.stderr
Labels: error-reporting, core

#463 Exhaustiveness fixes
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/matrix.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/exhaustiveness.rs
Labels: bug, error-reporting, pattern-matching

#467 Interned literals and numeric type suffixes
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-lexer/Cargo.toml
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/constant.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-source/src/string.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  tests/cases/should_fail/literals/integer_literal_too_large.hash
  tests/cases/should_fail/literals/integer_literal_too_large.stderr
Labels: parser, language

#471 Tc: diagnostics
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-lexer/src/error.rs
  compiler/hash-parser/src/diagnostics/mod.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-reporting/src/diagnostic.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/diagnostics/warning.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/exhaustiveness.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-utils/src/store.rs
  tests/cases/exhaustiveness/non-exhaustive-decl.hash
  tests/cases/exhaustiveness/non-exhaustive-decl.stderr
  tests/cases/exhaustiveness/overlapping_range_ends.hash
  tests/cases/exhaustiveness/overlapping_range_ends.stderr
  tests/cases/exhaustiveness/simple_unreachable_pats.hash
  tests/cases/exhaustiveness/simple_unreachable_pats.stderr
  tests/runner.rs
  tests/testing-internal/src/metadata.rs
Labels: error-reporting, typechecking, pattern-matching

#472 TC: support `...` patterns in constructor and tuple patterns
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/params.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/diagnostics/warning.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/fields.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/matrix.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/stack.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/exhaustiveness.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-vm/src/vm.rs
  tests/cases/exhaustiveness/non-exhaustive-constructor-field.hash
  tests/cases/exhaustiveness/non-exhaustive-constructor-field.stderr
  tests/cases/exhaustiveness/overlapping_range_ends.stderr
  tests/cases/exhaustiveness/simple_unreachable_pats.stderr
  tests/cases/exhaustiveness/tuples.hash
  tests/cases/tc/spread-pats/tuple-spread-pats.hash
  tests/cases/tc/structs/missing-fields.hash
  tests/cases/tc/structs/missing-fields.stderr
Labels: typechecking, pattern-matching

#476 Tc: error reporting and bug fixes
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/diagnostics/warning.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-source/src/location.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/warning.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-utils/src/printing.rs
  tests/cases/exhaustiveness/non-exhaustive-constructor-field.stderr
  tests/cases/should_fail/types/unclose_type_args.stderr
  tests/cases/tc/structs/constructor-binds.hash
  tests/cases/tc/structs/missing-fields.stderr
Labels: bug, typechecking

#478 tc: refactor `Term::{Merge|Union}` to use `TermListId`
  compiler/hash-alloc/src/collections/row.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/terms.rs
  compiler/hash-utils/src/printing.rs
  tests/testing-internal/src/metadata.rs
  tests/testing-macros/src/lib.rs
Labels: typechecking

#479 Semantics: guarantee diagnostic source order
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/diagnostics/warning.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/semantics/type_annotations/missing_struct_field_annotations.hash
  tests/cases/semantics/type_annotations/missing_struct_field_annotations.stderr
Labels: semantic-analysis

#481 parser: don't simplify parenthesised pattern if the only pattern is a spread pattern
  compiler/hash-parser/src/parser/pat.rs
Labels: bug, parser

#484 Add list tests and more primitive tests and fix some bugs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/exhaustiveness.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/typecheck/primitives/collections.hash
  tests/cases/typecheck/primitives/tuples.hash
Labels: typechecking

#485 tests: emit warnings for unrecognised keys and key-value pairs
  Cargo.lock
  tests/testing-internal/src/metadata.rs
  tests/testing-macros/Cargo.toml
  tests/testing-macros/src/lib.rs
Labels: tests

#486 Add typechecking function tests and fix bugs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/typecheck/functions/calling.hash
  tests/cases/typecheck/functions/inference.hash
  tests/cases/typecheck/functions/non-rt-arg.hash
  tests/cases/typecheck/functions/non-rt-arg.stderr
  tests/cases/typecheck/functions/non-rt-return.hash
  tests/cases/typecheck/functions/non-rt-return.stderr
  tests/cases/typecheck/functions/recursion.hash
Labels: tests, typechecking

#491 Do not build docs on CI
  .github/workflows/rust.yml
Labels: ci

#487 TC: Fix spread bug when the spread affects all tuple members and add test
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/pats.rs
  tests/cases/semantics/type_annotations/missing_struct_field_annotations.hash
  tests/cases/typecheck/spread-pats/tuple-spread-pats.hash
  tests/cases/typecheck/spread-pats/tuple-spread-pats.stderr
Labels: tests, typechecking

#493 TC: Add some basic nominal testing and fix a bug
  compiler/hash-typecheck/src/ops/bootstrap.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/params.rs
  tests/cases/typecheck/enums/adt.hash
  tests/cases/typecheck/enums/basic.hash
  tests/cases/typecheck/structs/basic.hash
  tests/cases/typecheck/structs/malformed-field-types.hash
  tests/cases/typecheck/structs/malformed-field-types.stderr
  tests/cases/typecheck/structs/pattern-matching.hash
Labels: tests, typechecking

#494 semantics: verify that fields of nominal definitions use consistent naming conventions.
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/params.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/origins.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/semantics/defs/naming_conventions.hash
  tests/cases/semantics/defs/naming_conventions.stderr
  tests/cases/semantics/type_annotations/missing_struct_field_annotations.stderr
Labels: semantic-analysis

#495 reporting: minimalise report code blocks
  compiler/hash-ast/src/ast.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
  tests/cases/typecheck/structs/missing-fields.stderr
  tests/cases/typecheck/traits/unspecified_member.hash
  tests/cases/typecheck/traits/unspecified_member.stderr
Labels: error-reporting, typechecking

#496 TC: Attach type information to nodes
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/nodes.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/typecheck/property_access/numeric_access_on_struct.stderr
  tests/cases/typecheck/property_access/out_of_bounds_access.stderr
  tests/cases/typecheck/spread-pats/tuple-spread-pats.stderr
Labels: typechecking, ast

#499 TC: fixes
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
  tests/cases/typecheck/spread-pats/tuple-spread-pats.stderr
  tests/runner.rs
Labels: tests, typechecking

#502 TC: Add unit nominal primitive
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/fields.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#505 TC: Polish trait validation checking and error reporting
  compiler/hash-ast/src/tree.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/cases/typecheck/traits/comppund_errors.hash
  tests/cases/typecheck/traits/comppund_errors.stderr
Labels: error-reporting, typechecking

#506 TC: Implement enums as unions
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/coerce.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/params.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  tests/cases/typecheck/enums/adt.hash
  tests/cases/typecheck/enums/basic.hash
Labels: typechecking
