Repository hash-org/hashc, pull requests merged in 2022-06, with the labels that each got.

#228 Parser: various fixes
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-token/src/lib.rs
  tests/parser/tests/cases/should_fail/dangling_parenthesis/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_spread_pattern/case.stderr
  tests/parser/tests/cases/should_fail/issue_223/case.hash
  tests/parser/tests/cases/should_fail/issue_223/case.stderr
  tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
  tests/parser/tests/cases/should_fail/pat_match_missing_semi/case.stderr
  tests/parser/tests/cases/should_fail/spread_pattern_in_namespace_pattern/case.stderr
  tests/parser/tests/cases/should_fail/spread_pattern_in_struct_pattern/case.stderr
  tests/parser/tests/test_runner.rs
Labels: parser

#230 Initial work for creating an IR stage within the compiler
  Cargo.lock
  Cargo.toml
  compiler/hash-ast-desugaring/Cargo.toml
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast/Cargo.toml
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/ident.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-hir/src/lib.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-interactive/src/lib.rs
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-lexer/Cargo.toml
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/import_resolver.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-reporting/Cargo.toml
  compiler/hash-source/Cargo.toml
  compiler/hash-token/Cargo.toml
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/refutability.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/storage.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/testing-macros/Cargo.toml
  compiler/hash-utils/testing-macros/src/lib.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/main.rs
  tests/parser/Cargo.toml
  tests/parser/benches/benches.rs
  tests/parser/tests/cases/should_fail/unclose_type_args/case.stderr
  tests/parser/tests/test_runner.rs
Labels: typechecking, organisation, ast

#231 Add scaffolding for the new typechecker
  compiler/hash-ast/src/ident.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/infer.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/refutability.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/state.rs
  compiler/hash-typecheck/src/storage.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/mods.rs
  compiler/hash-typecheck/src/storage/nominals.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/scope.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-typecheck/src/storage/state.rs
  compiler/hash-typecheck/src/storage/trts.rs
  compiler/hash-typecheck/src/storage/tys.rs
  compiler/hash-typecheck/src/storage/values.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/ty_builder.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
  compiler/hash/src/main.rs
Labels: typechecking, organisation

#237 refactor: use `From` utility traits for `StringLiteral` and `Identifier` instead of directly accessing maps
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/string.rs
  compiler/hash-token/src/lib.rs
Labels: organisation

#251 Pipeline revamp
  Cargo.lock
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-interactive/src/command.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-vm/src/vm.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/args.rs
  compiler/hash/src/main.rs
  tests/parser/tests/test_runner.rs
Labels: core

#253 parser: introduce `set` and `map` syntax
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-token/src/keyword.rs
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.hash
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_set_literal/case.hash
  tests/parser/tests/cases/should_fail/unclosed_set_literal/case.stderr
  tests/parser/tests/cases/should_pass/map_literals/case.hash
  tests/parser/tests/cases/should_pass/set_literals/case.hash
Labels: parser

#257 TC: Refactor the usage of both `Ty` and `Value`, and use only `Term`
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/scope.rs
  compiler/hash-typecheck/src/storage/state.rs
  compiler/hash-typecheck/src/storage/terms.rs
  compiler/hash-typecheck/src/storage/tys.rs
  compiler/hash-typecheck/src/storage/values.rs
  tests/parser/tests/test_runner.rs
Labels: typechecking

#260 Add `PrimitiveReader` to simplify accessing terms and other data
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/sources.rs
Labels: typechecking

#262 TC: Implement term substitutions in `Substitutor`
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#266 Semantics: implement `continue` and `break` outside of loop checking
  Cargo.lock
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-passes/Cargo.toml
  compiler/hash-ast-passes/src/error.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash/src/main.rs
Labels: semantic-analysis

#269 security: bump dashmap to >=5.1.0
  Cargo.lock
  compiler/hash-source/Cargo.toml
  compiler/hash-typecheck/Cargo.toml
Labels: mission-critical

#267 TC: Implement substitution unification
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#272 TC: Implement discovering free variables in a term
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#273 Semantics: implement checking of pattern semantic rules
  compiler/hash-ast-passes/src/analysis/error.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/error.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash/src/main.rs
Labels: semantic-analysis

#276 semantics: check that `return` statements are only used within functions
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/error.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-typecheck/src/storage/state.rs
Labels: semantic-analysis

#279 semantics: implement semantic checking of mutability and visibility modifiers
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/error.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/pattern.rs
Labels: semantic-analysis

#282 TC: Implement simplification of terms
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#281 semantics: implement warnings about useless expressions
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/error.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/analysis/warning.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
Labels: semantic-analysis

#286 TC: Implement getting the type of a term
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#287 semantics+ast: some minor refactoring and clean-up
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/diagnostics/warning.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/expression.rs
Labels: ast, semantic-analysis

#292 pipeline: continue running stages when diagnostics are only warnings
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-reporting/src/reporting.rs
  compiler/hash-vm/src/vm.rs
  tests/parser/tests/test_runner.rs
Labels: core

#298 TC: Implement term unification
  compiler/hash-source/src/identifier.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-utils/src/lib.rs
Labels: typechecking

#301 TC: Minor improvements to simplification and adding Root term
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#303 reporting: split logic into modules and fix span highlighting bug
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/diagnostics/warning.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-reporting/src/builder.rs
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-reporting/src/writer.rs
  compiler/hash-vm/src/error.rs
  compiler/hash-vm/src/vm.rs
  compiler/hash/src/main.rs
  tests/parser/tests/test_runner.rs
Labels: bug, error-reporting

#308 TC: Add scaffolding for AST traversal
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/infer.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/reporting.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/state.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash/src/main.rs
Labels: typechecking, ast

#309 reporting: implement `block` mode for larger spans
  compiler/hash-reporting/src/builder.rs
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-reporting/src/writer.rs
Labels: error-reporting

#313 TC: Implement validation of traits and modules
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#318 Add pre-commit hook for format/lint/test, and remove build step from CI.
  .github/workflows/rust.yml
  Cargo.lock
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash/Cargo.toml
Labels: enhancement, ci

#317 tc: Initial work for reporting within the typchecker
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/reporting.rs
  compiler/hash-typecheck/src/storage/arguments.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/params.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/terms.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: error-reporting, typechecking

#320 TC: Implement some traversal basics
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/reporting.rs
  compiler/hash-typecheck/src/storage/scope.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking, ast

#321 AST+TC: fix todos within the AST and add basic location information during tc traversal
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/reporting.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: error-reporting, typechecking, ast

#325 TC: Implement declarations and add validation to existing traversals
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/scope.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#338 TC: implement reporting for remaining members of `TcError`
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/params.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/diagnostics/symbol.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/reporting.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
Labels: error-reporting, typechecking

#344 TC: Implement traversal of function types, reference types, infer type
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking
