Repository hash-org/hashc, pull requests merged in 2022-07, with the labels that each got.

#347 TC: Implement traversal of type functions
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#350 parser: fix over eager token skipping in `parse_type_function`
  compiler/hash-parser/src/parser/types.rs
  tests/parser/tests/cases/should_pass/type_function_types/case.hash
Labels: bug, parser

#351 ast: Support `default` arguments on `TypeFunctionDefParam`
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: ast

#353 TC: Traverse merge types and type function calls
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-vm/src/stack.rs
Labels: typechecking

#349 pipeline: re-organise sources structure
  Cargo.lock
  compiler/hash-ast-desugaring/Cargo.toml
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/import_resolver.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/macros.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-reporting/src/writer.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash/src/crash_handler.rs
  compiler/hash/src/main.rs
  tests/parser/benches/benches.rs
  tests/parser/tests/test_runner.rs
Labels: parser, core

#355 Tc traverse `set` and `map` literals
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/sequence.rs
  tests/parser/tests/test_runner.rs
Labels: typechecking

#359 TC: Implement simplification of function calls
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
Labels: typechecking

#360 TC: Traverse function calls and constructors
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#356 Tc: implement traversal for more expressions and types
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#361 conventions: use standard naming conventions within `ast`, `parser` and `tc`
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: organisation, ast, conventions

#364 TC: Introduce unions and the "never" type
  Cargo.lock
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#365 tc: Implement nominal definition traversal and validation
  Cargo.lock
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/params.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-utils/src/printing.rs
  tests/parser/Cargo.toml
  tests/parser/tests/cases/should_fail/dangling_parenthesis/case.stderr
  tests/parser/tests/cases/should_fail/issue_223/case.stderr
  tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_literal_arrow/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_type/case.stderr
  tests/parser/tests/cases/should_fail/missing_comma_in_struct_field/case.stderr
  tests/parser/tests/cases/should_fail/pat_match_missing_semi/case.stderr
  tests/parser/tests/cases/should_fail/unclose_type_args/case.stderr
  tests/parser/tests/test_runner.rs
Labels: error-reporting, typechecking

#368 TC: Implement traversal for imports
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#369 tc: implement `mod` block traversals
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#370 tc: implement trait definition traversal
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/scope.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#371 tc: implement traversal for `trait impl`s and `impl` blocks
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#374 TC: Implement traversal of index expressions and property access
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#380 parser+ast: support for `union` type notation
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  docs/src/features/types.md
Labels: parser, ast

#382 ast+parser: introduce `merge_expr` variant
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-ast/src/operator.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-parser/src/parser/expression.rs
Labels: parser, ast

#386 TC: Add `Term::TyOf` in order to be able to perform algebra with types of terms
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  tests/parser/tests/test_runner.rs
Labels: typechecking

#392 Prelude injection
  Cargo.lock
  compiler/hash-ast-passes/Cargo.toml
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/diagnostics/directives.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/mod.rs
  compiler/hash-ast-passes/src/diagnostics/origins.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-pipeline/build.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash/src/main.rs
  stdlib/prelude.hash
  stdlib/string.hash
  tests/parser/tests/test_runner.rs
Labels: core

#396 TC: Factor out constant scope traversal
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
Labels: typechecking

#395 tc: Implement traversal of `binary` and `unary` expressions
  compiler/hash-typecheck/src/traverse/mod.rs
  stdlib/prelude.hash
Labels: typechecking

#398 TC: Implement patterns as typechecking primitives, and literal terms
  Cargo.lock
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/patterns.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking, pattern-matching

#404 ast+parser: Introduce `access` expr
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/analysis/block.rs
  compiler/hash-ast-passes/src/diagnostics/directives.rs
  compiler/hash-ast-passes/src/lib.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
  stdlib/prelude.hash
  tests/parser/tests/cases/should_fail/triple_colon_in_access_name/case.stderr
Labels: parser, ast

#406 TC: Implement getting the type and the term of a pattern
  compiler/hash-typecheck/src/ops/typing.rs
Labels: typechecking, pattern-matching

#411 TC: Implement pattern matching, as well as pattern and control flow traversal
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/patterns.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/sequence.rs
Labels: typechecking, pattern-matching

#413 parser+ast: remove `MethodCall` and finalise work on `Expr::Access`
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.stderr
  tests/parser/tests/cases/should_pass/issue_394/case.hash
Labels: parser, ast

#416 semantics: disallow float literals within patterns
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: semantic-analysis

#418 tc: traverse cast expressions
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-utils/src/path.rs
Labels: typechecking

#421 all: apply naming conventions to sources
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/analysis/mod.rs
  compiler/hash-ast-passes/src/analysis/pat.rs
  compiler/hash-ast-passes/src/diagnostics/directives.rs
  compiler/hash-ast-passes/src/diagnostics/error.rs
  compiler/hash-ast-passes/src/diagnostics/origins.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-source/src/string.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/pats.rs
  compiler/hash-typecheck/src/storage/patterns.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: conventions

#424 TC: Implement assignment and start dealing with recursive definitions
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/diagnostics/symbol.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking

#425 TC: implement caching for validation, unification, and simplification
  Cargo.lock
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/ops/cache.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/cache.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/traverse/mod.rs
Labels: typechecking, performance

#431 TC: implement, `spread`, `constructor`, `or`, and `list` patterns
  Cargo.lock
  compiler/hash-ast-desugaring/src/visitor.rs
  compiler/hash-ast-passes/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-pipeline/src/sources.rs
  compiler/hash-pipeline/src/traits.rs
  compiler/hash-reporting/src/macros.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-source/src/string.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/params.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/diagnostics/symbol.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/pats.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/sequence.rs
  compiler/hash-utils/testing-macros/Cargo.toml
  stdlib/.gitignore
  stdlib/prelude.hash
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.stderr
  tests/parser/tests/cases/should_fail/double_hash/case.stderr
  tests/parser/tests/cases/should_fail/triple_colon_in_access_name/case.stderr
  tests/parser/tests/cases/should_pass/literal_pattern_decl/case.hash
Labels: typechecking, pattern-matching

#432 TC: New Var terms for scopes and bounds
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/diagnostics/reporting.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/ops/building.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/mod.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/core.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
Labels: typechecking

#433 TC: Bug fixing
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-typecheck/src/traverse/scopes.rs
Labels: typechecking

#434 WIP: Tc: Exhaustiveness
  Cargo.lock
  compiler/hash-source/src/lib.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/mod.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/fmt.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/cache.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/storage/location.rs
  compiler/hash-typecheck/src/storage/primitives.rs
  compiler/hash-typecheck/src/storage/sources.rs
  compiler/hash-typecheck/src/traverse/mod.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/lib.rs
  compiler/hash-utils/src/stack.rs
Labels: typechecking, pattern-matching
