Repository hash-org/hashc, pull requests merged in 2022-05, with the labels that each got.

#172 Unsafe expressions
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/count.rs
  compiler/hash-ast/src/keyword.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-parser/src/lexer.rs
  compiler/hash-parser/src/token.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/unsafe_blocks/case.hash
Labels: parser

#173 Parser: support for defining default values for function arguments.
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_fail/missing_default_value_in_function_literal/case.hash
  tests/parser/tests/cases/should_fail/missing_type_in_function_literal/case.hash
  tests/parser/tests/cases/should_pass/function_literal_with_default_value/case.hash
Labels: parser

#174 Language: Implement named tuples
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/count.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-parser/src/token.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/types.rs
  compiler/hash-typecheck/src/unify.rs
  compiler/hash-typecheck/src/writer.rs
  docs/src/advanced/loop-transpilation.md
  docs/src/basics/conditionals.md
  docs/src/basics/directives.md
  docs/src/basics/enum-types.md
  docs/src/basics/functions.md
  docs/src/basics/generics-polymorphism.md
  docs/src/basics/loops.md
  docs/src/basics/modules.md
  docs/src/basics/operators.md
  docs/src/basics/pattern-matching.md
  docs/src/basics/primitive-types.md
  docs/src/basics/struct-types.md
  docs/src/basics/types-assertions.md
  docs/src/basics/variables.md
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_name_assignment/case.hash
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_type_annotation/case.hash
  tests/parser/tests/cases/should_fail/incomplete_tuple_type/case.hash
  tests/parser/tests/cases/should_pass/tuple_literals/case.hash
  tests/parser/tests/cases/should_pass/tuple_types/case.hash
Labels: parser

#175 Parser: implement named arguments within function calls
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/count.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/error.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash-typecheck/src/unify.rs
  tests/parser/tests/cases/should_fail/double_comma_in_function_call/case.hash
  tests/parser/tests/cases/should_fail/missing_expression_in_function_call/case.hash
  tests/parser/tests/cases/should_pass/function_call_with_named_arguments/case.hash
Labels: parser

#176 Add documentation for the new syntax for generics and traits
  compiler/hash-typecheck/src/ty_builder.rs
  docs/src/SUMMARY.md
  docs/src/basics/generics-polymorphism.md
  docs/src/basics/generics.md
  docs/src/basics/traits.md
Labels: documentation

#178 Parser: Separate `ast-gen` into specific files
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-parser/src/import_resolver.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/statement.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-typecheck/src/traverse.rs
  compiler/hash/src/main.rs
  tests/parser/tests/test_runner.rs
Labels: parser

#185 parser: Implement spread patterns, within tuples and lists
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/count.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-typecheck/src/refutability.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_fail/incomplete_list_pattern/case.hash
  tests/parser/tests/cases/should_fail/incomplete_spread_pattern/case.hash
  tests/parser/tests/cases/should_fail/spread_pattern_in_namespace_pattern/case.hash
  tests/parser/tests/cases/should_fail/spread_pattern_in_struct_pattern/case.hash
  tests/parser/tests/cases/should_pass/list_patterns/case.hash
  tests/parser/tests/cases/should_pass/list_patterns_in_match_cases/case.hash
  tests/parser/tests/cases/should_pass/spread_pattern_in_tuple/case.hash
  tests/parser/tests/cases/should_pass/xor_in_match/case.hash
Labels: parser, language

#189 Restructure documentation structure and contents
  docs/src/SUMMARY.md
  docs/src/basics/directives.md
  docs/src/basics/enum-types.md
  docs/src/basics/functions.md
  docs/src/basics/loops.md
  docs/src/basics/prelude.md
  docs/src/basics/primitive-types.md
  docs/src/basics/reference.md
  docs/src/basics/types-assertions.md
  docs/src/basics/types.md
  docs/src/basics/variables.md
  docs/src/features/control-flow.md
  docs/src/features/directives.md
  docs/src/features/functions.md
  docs/src/features/intro.md
  docs/src/features/memory.md
  docs/src/features/modules.md
  docs/src/features/operators.md
  docs/src/features/patterns.md
  docs/src/features/primitives.md
  docs/src/features/structs-enums.md
  docs/src/features/traits.md
  docs/src/features/type-functions.md
  docs/src/features/variables.md
  docs/src/intro.md
Labels: documentation

#187 Parser: New struct enum syntax
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/count.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/statement.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/empty_for_loop/case.hash
  tests/parser/tests/cases/should_pass/empty_struct_literal/case.hash
  tests/parser/tests/cases/should_pass/intrinsics/case.hash
  tests/parser/tests/cases/should_pass/list_patterns/case.hash
  tests/parser/tests/cases/should_pass/referencing_structs/case.hash
  tests/parser/tests/cases/should_pass/struct_literal_init/case.hash
Labels: parser

#192 Add documentation section about functions
  docs/src/SUMMARY.md
  docs/src/features/functions.md
  docs/src/features/intro.md
  docs/src/features/name-bindings.md
Labels: documentation

#193 Add documentation section about type functions
  docs/src/features/functions.md
  docs/src/features/type-functions.md
Labels: documentation

#194 Add documentation section on structs and enums
  docs/src/features/structs-enums.md
Labels: documentation

#197 Language: Add `ConstructPattern` and remove `StructPattern`
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-typecheck/src/refutability.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/block_return/case.hash
  tests/parser/tests/cases/should_pass/compount_pattern_matching_with_structs/case.hash
  tests/parser/tests/cases/should_pass/nested_match/case.hash
  tests/parser/tests/cases/should_pass/parenthesised_match_statement/case.hash
  tests/parser/tests/cases/should_pass/pattern_matching_let/case.hash
  tests/parser/tests/cases/should_pass/struct_pattern_matching/case.hash
Labels: language

#198 Add documentation about traits and implementations
  docs/src/SUMMARY.md
  docs/src/features/traits-impls.md
Labels: documentation

#200 Write documentation section about modules and visibility
  docs/src/SUMMARY.md
  docs/src/features/modules.md
Labels: documentation

#207 Docs: Add initial grammar for types
  docs/src/features/functions.md
  docs/src/features/primitives.md
  docs/src/features/type-functions.md
  docs/src/features/types.md
Labels: documentation

#205 Language: Support new trait syntax and type functions defs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/declarations/case.hash
  tests/parser/tests/cases/should_pass/existential_type/case.hash
  tests/parser/tests/cases/should_pass/let_statements/case.hash
  tests/parser/tests/cases/should_pass/traits_defns/case.hash
Labels: language

#208 Add book link to Types section
  docs/src/SUMMARY.md
Labels: documentation

#209 Docs: Update documentation on patterns
  docs/src/SUMMARY.md
  docs/src/features/patterns.md
Labels: documentation

#211 Add a function type to the grammar of types
  docs/src/features/types.md
Labels: documentation

#212 Docs: Remove unnecessary ":=" variant in type function arguments
  docs/src/features/types.md
Labels: documentation

#213 Parser: Refine type parsing
  compiler/hash-alloc/src/collections/row.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/literal.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/operator.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/existential_type/case.hash
Labels: parser, language

#214 AST: remove visitor methods for traversing grouped types
  compiler/hash-ast/src/tree.rs
  compiler/hash-typecheck/src/traverse.rs
Labels: ast

#215 Parser: Added declaration visibility
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/visibility/case.hash
Labels: language

#216 Language: Add support for mutability modifiers
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pattern.rs
  compiler/hash-parser/src/parser/types.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/mutability/case.hash
Labels: ast, language

#217 Language: Add `mod` blocks to parser and AST.
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/mod_blocks/case.hash
Labels: ast, language

#220 Language: add support for `type` expressions
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/traits_defns/case.hash
  tests/parser/tests/cases/should_pass/type_exprs/case.hash
Labels: ast, language

#221 Language: support trait implementation definition constructs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-ast/src/visitor.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-token/src/keyword.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/traverse.rs
  tests/parser/tests/cases/should_pass/impl_blocks/case.hash
Labels: language

#219 Parser: Use `as` syntax in namespace patterns
  compiler/hash-parser/src/parser/pattern.rs
  docs/src/features/patterns.md
  tests/parser/tests/cases/should_pass/pattern_matching_let/case.hash
Labels: parser

#225 stdlib: Update syntax to match the current specification
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-parser/src/parser/pattern.rs
  stdlib/io.hash
  stdlib/iter.hash
  stdlib/list.hash
  stdlib/num.hash
  stdlib/prelude.hash
Labels: standard-library

#227 tests: Add UI test capabilities for `should_fail` cases
  Cargo.lock
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/error.rs
  compiler/hash-parser/src/parser/expression.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-reporting/src/reporting.rs
  compiler/hash-typecheck/src/error.rs
  tests/parser/Cargo.toml
  tests/parser/tests/cases/should_fail/char_literals/case.stderr
  tests/parser/tests/cases/should_fail/dangling_paren_tree/case.stderr
  tests/parser/tests/cases/should_fail/dangling_parenthesis/case.stderr
  tests/parser/tests/cases/should_fail/double_colon_in_map_literal/case.stderr
  tests/parser/tests/cases/should_fail/double_comma_in_function_call/case.stderr
  tests/parser/tests/cases/should_fail/double_comma_in_list_literal/case.stderr
  tests/parser/tests/cases/should_fail/double_hash/case.stderr
  tests/parser/tests/cases/should_fail/empty_type_args/case.stderr
  tests/parser/tests/cases/should_fail/expresionless_directive/case.stderr
  tests/parser/tests/cases/should_fail/goodbye_world/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_list_pattern/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_spread_pattern/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_name_assignment/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_literal_type_annotation/case.stderr
  tests/parser/tests/cases/should_fail/incomplete_tuple_type/case.stderr
  tests/parser/tests/cases/should_fail/integer_literal_too_large/case.stderr
  tests/parser/tests/cases/should_fail/invalid_float_exponent/case.stderr
  tests/parser/tests/cases/should_fail/invalid_unicode_char/case.stderr
  tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_literal_arrow/case.hash
  tests/parser/tests/cases/should_fail/malformed_function_literal_arrow/case.stderr
  tests/parser/tests/cases/should_fail/malformed_function_type/case.hash
  tests/parser/tests/cases/should_fail/malformed_function_type/case.stderr
  tests/parser/tests/cases/should_fail/malformed_list_literal/case.stderr
  tests/parser/tests/cases/should_fail/missing_comma_in_struct_field/case.hash
  tests/parser/tests/cases/should_fail/missing_comma_in_struct_field/case.stderr
  tests/parser/tests/cases/should_fail/missing_default_value_in_function_literal/case.stderr
  tests/parser/tests/cases/should_fail/missing_expression_in_function_call/case.stderr
  tests/parser/tests/cases/should_fail/missing_raw_ref_type/case.hash
  tests/parser/tests/cases/should_fail/missing_raw_ref_type/case.stderr
  tests/parser/tests/cases/should_fail/missing_ref_type/case.hash
  tests/parser/tests/cases/should_fail/missing_ref_type/case.stderr
  tests/parser/tests/cases/should_fail/missing_type_in_function_literal/case.stderr
  tests/parser/tests/cases/should_fail/multi_code_point_char_literal/case.stderr
  tests/parser/tests/cases/should_fail/non_existant_import/case.stderr
  tests/parser/tests/cases/should_fail/non_hex_ascii_escape_code/case.stderr
  tests/parser/tests/cases/should_fail/non_hex_unicode_char/case.stderr
  tests/parser/tests/cases/should_fail/pat_match_missing_semi/case.stderr
  tests/parser/tests/cases/should_fail/short_ascii_code/case.stderr
  tests/parser/tests/cases/should_fail/spread_pattern_in_namespace_pattern/case.stderr
  tests/parser/tests/cases/should_fail/spread_pattern_in_struct_pattern/case.hash
  tests/parser/tests/cases/should_fail/spread_pattern_in_struct_pattern/case.stderr
  tests/parser/tests/cases/should_fail/triple_colon_in_access_name/case.stderr
  tests/parser/tests/cases/should_fail/unclose_type_args/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_char_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_set_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_string_literal/case.stderr
  tests/parser/tests/cases/should_fail/unclosed_unicode_literal/case.stderr
  tests/parser/tests/cases/should_fail/unknown_escape_sequence/case.stderr
  tests/parser/tests/test_runner.rs
Labels: tests
