Repository hash-org/hashc, pull requests merged in 2022-04, with the labels that each got.

#154 parser: Empty tuple syntax `()`
  compiler/hash-parser/src/error.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-parser/src/lexer.rs
  compiler/hash-source/src/location.rs
  tests/parser/tests/cases/should_pass/tuple_literals/case.hash
  tests/parser/tests/cases/should_pass/tuple_types/case.hash
Labels: parser

#161 report: fix issue with operator locations being under reported.
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/traverse.rs
Labels: bug, error-reporting

#162 Typechecking: Fix boolean patterns
  compiler/hash-typecheck/src/traverse.rs
Labels: typechecking

#165 Fix while transformation
  compiler/hash-ast/src/operator.rs
  compiler/hash-parser/src/gen.rs
Labels: bug

#168 Reporting: More accurate error locations for unresolved symbols
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-parser/src/gen.rs
  compiler/hash-typecheck/src/error.rs
  compiler/hash-typecheck/src/scope.rs
  compiler/hash-typecheck/src/traverse.rs
Labels: error-reporting

#169 reporting: fix issue where access name locations were inaccurate
  compiler/hash-typecheck/src/traverse.rs
Labels: bug, error-reporting
