Repository hash-org/hashc, pull requests merged in 2022-11, with the labels that each got.

#559 Add the ability to assign `ScopeId`s to AST nodes
  compiler/hash-typecheck/src/traverse/scopes.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/nodes.rs
Labels: ast, semantic-analysis

#556 Add new definitions in `hash-types`
  compiler/hash-ir/src/ir.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/params.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/reader.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/args.rs
  compiler/hash-types/src/builder.rs
  compiler/hash-types/src/lib.rs
  compiler/hash-types/src/location.rs
  compiler/hash-types/src/new/args.rs
  compiler/hash-types/src/new/control.rs
  compiler/hash-types/src/new/data.rs
  compiler/hash-types/src/new/defs.rs
  compiler/hash-types/src/new/fns.rs
  compiler/hash-types/src/new/holes.rs
  compiler/hash-types/src/new/mod.rs
  compiler/hash-types/src/new/mods.rs
  compiler/hash-types/src/new/params.rs
  compiler/hash-types/src/new/pats.rs
  compiler/hash-types/src/new/refs.rs
  compiler/hash-types/src/new/scopes.rs
  compiler/hash-types/src/new/symbols.rs
  compiler/hash-types/src/new/terms.rs
  compiler/hash-types/src/new/trts.rs
  compiler/hash-types/src/new/tuples.rs
  compiler/hash-types/src/new/tys.rs
  compiler/hash-types/src/new/unions.rs
  compiler/hash-types/src/new/vars.rs
  compiler/hash-types/src/storage.rs
  compiler/hash-types/src/terms.rs
Labels: typechecking

#561 Add patterns and literals to the new term structure.
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/new/access.rs
  compiler/hash-types/src/new/args.rs
  compiler/hash-types/src/new/control.rs
  compiler/hash-types/src/new/data.rs
  compiler/hash-types/src/new/defs.rs
  compiler/hash-types/src/new/lits.rs
  compiler/hash-types/src/new/mod.rs
  compiler/hash-types/src/new/pats.rs
  compiler/hash-types/src/new/scopes.rs
  compiler/hash-types/src/new/terms.rs
  compiler/hash-types/src/new/tuples.rs
Labels: typechecking, pattern-matching

#562 IR: introduce `IrTy` to represent types at the IR level
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/cfg.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-types/src/terms.rs
Labels: lowering

#565 Add definitions for context in new term structure
  Cargo.lock
  compiler/hash-types/Cargo.toml
  compiler/hash-types/src/new/access.rs
  compiler/hash-types/src/new/args.rs
  compiler/hash-types/src/new/casting.rs
  compiler/hash-types/src/new/context.rs
  compiler/hash-types/src/new/data.rs
  compiler/hash-types/src/new/defs.rs
  compiler/hash-types/src/new/fns.rs
  compiler/hash-types/src/new/mod.rs
  compiler/hash-types/src/new/mods.rs
  compiler/hash-types/src/new/params.rs
  compiler/hash-types/src/new/scopes.rs
  compiler/hash-types/src/new/symbols.rs
  compiler/hash-types/src/new/terms.rs
  compiler/hash-types/src/new/trts.rs
  compiler/hash-types/src/new/tys.rs
  compiler/hash-types/src/new/vars.rs
  compiler/hash-utils/src/store.rs
Labels: typechecking

#568 lower: implement logic for converting `Term`s into `IrTy`s for the IR builder
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-source/src/identifier.rs
Labels: lowering

#572 IR: Begin lowering variable expressions 🎉 🥳
  compiler/hash-ast-expand/src/visitor.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/nodes.rs
  compiler/hash-untyped-semantics/src/analysis/block.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/cases/semantics/directives/dump_ir.hash
Labels: lowering

#585 IR: lower primitive literal constants and declarations
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-source/src/location.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/nodes.rs
Labels: lowering

#587 IR: lower `loop`, `break`, `continue` and `return` statements
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/cfg.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
Labels: lowering

#590 typechecker: introduce workaround for currently broken trait resolution
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
Labels: typechecking

#592 pipeline: introduce `Target` to denote what compilation target the compiler is compiling to
  Cargo.lock
  Cargo.toml
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-reporting/src/errors.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-target/Cargo.toml
  compiler/hash-target/src/lib.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-types/Cargo.toml
  compiler/hash-types/src/storage.rs
  compiler/hash-types/src/terms.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/args.rs
  compiler/hash/src/main.rs
Labels: core

#593 lower: implement `{binary+unary}` operators, function calls, indexing, field access
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/category.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-typecheck/src/ops/discover.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/substitute.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/traverse/operators.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/bootstrap.rs
  compiler/hash-types/src/builder.rs
  compiler/hash-types/src/terms.rs
Labels: lowering

#594 IR: allow for IR to be emitted using `.dot` syntax for Graphviz
  Cargo.lock
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-ir/src/write.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/settings.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/args.rs
  compiler/hash/src/main.rs
Labels: lowering
