Repository hash-org/hashc, pull requests merged in 2022-12, with the labels that each got.

#595 TC(new): Scope discovery pass (1)
  Cargo.lock
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-reporting/src/diagnostic.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/new/ctx.rs
  compiler/hash-typecheck/src/new/diagnostics/error.rs
  compiler/hash-typecheck/src/new/diagnostics/mod.rs
  compiler/hash-typecheck/src/new/diagnostics/panic.rs
  compiler/hash-typecheck/src/new/diagnostics/store.rs
  compiler/hash-typecheck/src/new/diagnostics/warning.rs
  compiler/hash-typecheck/src/new/env.rs
  compiler/hash-typecheck/src/new/environment/ast_info.rs
  compiler/hash-typecheck/src/new/environment/mod.rs
  compiler/hash-typecheck/src/new/environment/tc_env.rs
  compiler/hash-typecheck/src/new/mod.rs
  compiler/hash-typecheck/src/new/ops/common.rs
  compiler/hash-typecheck/src/new/ops/data.rs
  compiler/hash-typecheck/src/new/ops/defs.rs
  compiler/hash-typecheck/src/new/ops/infer.rs
  compiler/hash-typecheck/src/new/ops/mod.rs
  compiler/hash-typecheck/src/new/ops/mods.rs
  compiler/hash-typecheck/src/new/ops/stack.rs
  compiler/hash-typecheck/src/new/ops/tuple.rs
  compiler/hash-typecheck/src/new/passes/ast_ops.rs
  compiler/hash-typecheck/src/new/passes/ast_pass.rs
  compiler/hash-typecheck/src/new/passes/mod.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolving.rs
  compiler/hash-typecheck/src/new/primitives/mod.rs
  compiler/hash-typecheck/src/new/primitives/subs.rs
  compiler/hash-typecheck/src/storage/mod.rs
  compiler/hash-types/Cargo.toml
  compiler/hash-types/src/new/access.rs
  compiler/hash-types/src/new/args.rs
  compiler/hash-types/src/new/casting.rs
  compiler/hash-types/src/new/data.rs
  compiler/hash-types/src/new/defs.rs
  compiler/hash-types/src/new/environment/context.rs
  compiler/hash-types/src/new/environment/env.rs
  compiler/hash-types/src/new/environment/mod.rs
  compiler/hash-types/src/new/environment/source_info.rs
  compiler/hash-types/src/new/environment/stores.rs
  compiler/hash-types/src/new/fns.rs
  compiler/hash-types/src/new/holes.rs
  compiler/hash-types/src/new/locations.rs
  compiler/hash-types/src/new/mod.rs
  compiler/hash-types/src/new/mods.rs
  compiler/hash-types/src/new/params.rs
  compiler/hash-types/src/new/scopes.rs
  compiler/hash-types/src/new/symbols.rs
  compiler/hash-types/src/new/terms.rs
  compiler/hash-types/src/new/trts.rs
  compiler/hash-types/src/new/tuples.rs
  compiler/hash-types/src/new/tys.rs
  compiler/hash-utils/src/store.rs
Labels: typechecking

#596 source: re-work constants and start lowering `match`es
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-lexer/Cargo.toml
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/matches.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/constant.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-target/src/size.rs
  compiler/hash-typecheck/src/exhaustiveness/constant.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/range.rs
  compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/validate.rs
  compiler/hash-types/src/pats.rs
  compiler/hash-types/src/terms.rs
  compiler/hash/src/args.rs
Labels: core, lowering

#597 ast: move `Impl` and `Mod` into their own `Expr`s out of `Block`
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-untyped-semantics/src/diagnostics/directives.rs
  compiler/hash-untyped-semantics/src/visitor.rs
Labels: ast

#614 Reporting: Better fluent API for creating reports
  compiler/hash-lexer/src/error.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/diagnostics/mod.rs
  compiler/hash-parser/src/diagnostics/warning.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-reporting/src/builder.rs
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/macros.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-reporting/src/reporter.rs
  compiler/hash-reporting/src/writer.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/diagnostics/macros.rs
  compiler/hash-typecheck/src/diagnostics/mod.rs
  compiler/hash-typecheck/src/diagnostics/warning.rs
  compiler/hash-typecheck/src/new/diagnostics/error.rs
  compiler/hash-typecheck/src/new/diagnostics/panic.rs
  compiler/hash-typecheck/src/new/diagnostics/warning.rs
  compiler/hash-typecheck/src/new/ops/oracle.rs
  compiler/hash-types/src/new/pats.rs
  compiler/hash-untyped-semantics/src/diagnostics/error.rs
  compiler/hash-untyped-semantics/src/diagnostics/mod.rs
  compiler/hash-untyped-semantics/src/diagnostics/warning.rs
  compiler/hash-untyped-semantics/src/lib.rs
  compiler/hash-vm/src/error.rs
  tests/runner.rs
Labels: error-reporting

#616 tc+exhaustiveness: add partial support for exhaustiveness checking for `enum`s
  Cargo.lock
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-typecheck/src/exhaustiveness/construct.rs
  compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
  compiler/hash-typecheck/src/exhaustiveness/fields.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/scope.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/typing.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-types/src/builder.rs
  compiler/hash-types/src/nominals.rs
  compiler/hash-types/src/terms.rs
  tests/cases/typecheck/enums/basic.hash
  tests/runner.rs
Labels: typechecking, pattern-matching

#619 lowering: support lowering `enum`, `struct`, `(a, b)` and `[a, b, c]` as `RValue`s
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/cfg.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-typecheck/src/diagnostics/error.rs
  compiler/hash-typecheck/src/ops/oracle.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
Labels: lowering

#621 lower: correctly handle logical operator short-circuiting
  compiler/hash-ast/src/ast.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-token/src/lib.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  tests/cases/parser/literals/overeager_tuple_lit_entry.hash
Labels: lowering

#623 lower: support lowering constant blocks
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/origin.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/discover.rs
Labels: lowering

#624 lowering: introduce a optimisation pass manager for the IR
  compiler/hash-ir/src/basic_blocks.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-lexer/src/utils.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-lower/src/optimise/mod.rs
  compiler/hash-lower/src/optimise/simplify.rs
  compiler/hash-lower/src/traversal.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-session/src/lib.rs
  compiler/hash/src/args.rs
Labels: lowering

#625 Traverse functions and blocks in scope discovery
  compiler/hash-typecheck/src/new/ops/fns.rs
  compiler/hash-typecheck/src/new/ops/mod.rs
  compiler/hash-typecheck/src/new/ops/mods.rs
  compiler/hash-typecheck/src/new/ops/params.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-types/src/new/mods.rs
Labels: typechecking

#626 Implement scope discovery for structs and enums
  compiler/hash-typecheck/src/new/ops/data.rs
  compiler/hash-typecheck/src/new/ops/params.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
Labels: typechecking

#628 Add unsupported error message for merge declarations
  compiler/hash-typecheck/src/new/diagnostics/error.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
Labels: typechecking

#635 Implement entering scopes during AST traversal in symbol resolution
  compiler/hash-typecheck/src/new/environment/ast_info.rs
  compiler/hash-typecheck/src/new/ops/ast.rs
  compiler/hash-typecheck/src/new/ops/common.rs
  compiler/hash-typecheck/src/new/ops/context.rs
  compiler/hash-typecheck/src/new/ops/data.rs
  compiler/hash-typecheck/src/new/ops/mod.rs
  compiler/hash-typecheck/src/new/passes/mod.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution.rs
  compiler/hash-types/src/new/environment/context.rs
Labels: typechecking

#636 lower: support almost full range of patterns in declarations
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/optimise.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/pat.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/ops/pats.rs
Labels: lowering

#640 ast: remove `Pat::Spread`
  compiler/hash-ast-desugaring/src/desugaring.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-ast/src/origin.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/diagnostics/mod.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-untyped-semantics/src/analysis/mod.rs
  compiler/hash-untyped-semantics/src/analysis/pat.rs
  compiler/hash-untyped-semantics/src/diagnostics/error.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/cases/semantics/pats/multiple_spread.stderr
Labels: ast, lowering

#641 IR: implement a basic visitor for mutable context, and a modifying visitor
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-utils/src/store.rs
  compiler/hash/src/args.rs
Labels: lowering

#643 Add a `CellStore` to avoid unnecessary clones with stores
  Cargo.lock
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/store.rs
Labels: alloc

#644 ir+lowering improvements
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/cfg.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-lower/src/optimise/simplify.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/ops/cache.rs
  compiler/hash-typecheck/src/ops/simplify.rs
  compiler/hash-typecheck/src/ops/unify.rs
  compiler/hash-typecheck/src/storage/cache.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-utils/src/store.rs
Labels: performance, lowering

#663 Add a symbol resolution pass to the typechecker
  compiler/hash-ast/src/ast.rs
  compiler/hash-typecheck/src/new/diagnostics/error.rs
  compiler/hash-typecheck/src/new/diagnostics/mod.rs
  compiler/hash-typecheck/src/new/diagnostics/params.rs
  compiler/hash-typecheck/src/new/diagnostics/warning.rs
  compiler/hash-typecheck/src/new/ops/common.rs
  compiler/hash-typecheck/src/new/ops/context.rs
  compiler/hash-typecheck/src/new/ops/data.rs
  compiler/hash-typecheck/src/new/ops/infer.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution.rs
  compiler/hash-types/src/new/access.rs
  compiler/hash-types/src/new/args.rs
  compiler/hash-types/src/new/environment/context.rs
  compiler/hash-types/src/new/locations.rs
  compiler/hash-types/src/new/mods.rs
  compiler/hash-types/src/new/params.rs
  compiler/hash-types/src/new/scopes.rs
  compiler/hash-types/src/new/terms.rs
  compiler/hash-types/src/new/tys.rs
  compiler/hash-utils/src/lib.rs
  compiler/hash-utils/src/state.rs
Labels: typechecking

#666 source: Shrink `SourceId` from 12 bytes to 4 bytes
  Cargo.lock
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-expand/src/lib.rs
  compiler/hash-ast/Cargo.toml
  compiler/hash-ast/src/node_map.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-pipeline/src/interface.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/traverse/visitor.rs
  compiler/hash-untyped-semantics/src/lib.rs
  compiler/hash-vm/src/stack.rs
Labels: performance

#668 Resolve patterns during symbol resolution
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-typecheck/src/exhaustiveness/lower.rs
  compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
  compiler/hash-typecheck/src/new/diagnostics/error.rs
  compiler/hash-typecheck/src/new/ops/ast.rs
  compiler/hash-typecheck/src/new/ops/common.rs
  compiler/hash-typecheck/src/new/ops/mod.rs
  compiler/hash-typecheck/src/new/ops/params.rs
  compiler/hash-typecheck/src/new/passes/ast_pass.rs
  compiler/hash-typecheck/src/new/passes/scope_discovery.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/exprs.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/mod.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/paths.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/pats.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/tys.rs
  compiler/hash-typecheck/src/new/passes/symbol_resolution/visitor.rs
  compiler/hash-typecheck/src/ops/params.rs
  compiler/hash-typecheck/src/ops/pats.rs
  compiler/hash-typecheck/src/ops/scope.rs
Labels: typechecking
