Repository hash-org/hashc, pull requests merged in 2023-09, with the labels that each got.

#944 Fill the `origin` fields of all TIR nodes
  compiler/hash-ast-expand/src/attr.rs
  compiler/hash-attrs/src/builtin.rs
  compiler/hash-exhaustiveness/src/lib.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/ctx.rs
  compiler/hash-semantics/src/ops/bootstrap.rs
  compiler/hash-semantics/src/passes/ast_utils.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/mod.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/building.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/holes.rs
  compiler/hash-tir/src/node.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/primitives.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/symbols.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  tests/cases/typecheck/property_access/out_of_bounds_access.stderr
Labels: type-system

#957 re-implement `#dump_ast` and re-organise AST printing code
  Cargo.lock
  compiler/hash-ast-expand/Cargo.toml
  compiler/hash-ast-expand/src/attr.rs
  compiler/hash-ast-expand/src/diagnostics/error.rs
  compiler/hash-ast-expand/src/diagnostics/mod.rs
  compiler/hash-ast-expand/src/expander.rs
  compiler/hash-ast-expand/src/lib.rs
  compiler/hash-ast-expand/src/visitor.rs
  compiler/hash-ast-utils/Cargo.toml
  compiler/hash-ast-utils/src/attr.rs
  compiler/hash-ast-utils/src/dump.rs
  compiler/hash-ast-utils/src/lib.rs
  compiler/hash-ast-utils/src/pretty/collection.rs
  compiler/hash-ast-utils/src/pretty/config.rs
  compiler/hash-ast-utils/src/pretty/mod.rs
  compiler/hash-ast-utils/src/pretty/state.rs
  compiler/hash-ast-utils/src/tree.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-attrs/Cargo.toml
  compiler/hash-attrs/src/builtin.rs
  compiler/hash-attrs/src/checks.rs
  compiler/hash-attrs/src/diagnostics.rs
  compiler/hash-attrs/src/lib.rs
  compiler/hash-attrs/src/ty.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/lib.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/main.rs
  tests/cases/attributes/unknown_directive.stdout
Labels: ast, fmt

#959 Remove location store and use `node.origin` for TIR reporting
  compiler/hash-ast-expand/src/attr.rs
  compiler/hash-exhaustiveness/src/construct.rs
  compiler/hash-exhaustiveness/src/deconstruct.rs
  compiler/hash-exhaustiveness/src/diagnostics.rs
  compiler/hash-exhaustiveness/src/fields.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/ctx.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/environment/ast_info.rs
  compiler/hash-semantics/src/environment/mod.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/mod.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/arrays.rs
  compiler/hash-tir/src/atom_info.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/locations.rs
  compiler/hash-tir/src/node.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/mod.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  tests/cases/typecheck/structs/missing-fields.stderr
Labels: type-system

#961 TIR: Merge `Ty` and `Term` enums
  compiler/hash-ast-expand/src/attr.rs
  compiler/hash-ast-expand/src/diagnostics/error.rs
  compiler/hash-attrs/src/builtin.rs
  compiler/hash-exhaustiveness/src/constant.rs
  compiler/hash-exhaustiveness/src/construct.rs
  compiler/hash-exhaustiveness/src/deconstruct.rs
  compiler/hash-exhaustiveness/src/fields.rs
  compiler/hash-exhaustiveness/src/lib.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-exhaustiveness/src/range.rs
  compiler/hash-exhaustiveness/src/usefulness.rs
  compiler/hash-exhaustiveness/src/wildcard.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-lower/src/build/category.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-semantics/src/environment/ast_info.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/atom_info.rs
  compiler/hash-tir/src/building.rs
  compiler/hash-tir/src/casting.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/node.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/refs.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: type-system

#965 TIR tweaks: Rename some variants, simplify loops, and make `Decl` specific to blocks
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/category.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-semantics/src/environment/ast_info.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-storage/src/store/statics.rs
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-tir/src/control.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/lits.rs
  compiler/hash-tir/src/mods.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  tests/cases/typecheck/property_access/out_of_bounds_access.stderr
Labels: type-system

#979 semantics: implement pattern bind checking
  compiler/hash-driver/src/driver.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-semantics/src/diagnostics/definitions.rs
  compiler/hash-semantics/src/diagnostics/reporting.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/mod.rs
  compiler/hash-semantics/src/passes/resolution/pat_binds.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  tests/cases/typecheck/pat_binds/548.hash
  tests/cases/typecheck/pat_binds/548.stderr
  tests/cases/typecheck/pat_binds/different_binds.hash
  tests/cases/typecheck/pat_binds/different_binds.stderr
  tests/cases/typecheck/pat_binds/duplicate_binds.hash
  tests/cases/typecheck/pat_binds/duplicate_binds.stderr
  tests/cases/typecheck/pat_binds/multiple_invalid_binds.hash
  tests/cases/typecheck/pat_binds/multiple_invalid_binds.stderr
  tests/disabled-cases/patterns/548.stderr
  tests/disabled-cases/patterns/multiple_invalid_binds.stderr
Labels: semantic-analysis, pattern-matching

#984 TIR: Add `Map` and `Visit` traits to the `tir::Visitor` in order to reduce code duplication
  compiler/hash-lower/src/discover.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/visitor.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: type-system, organisation

#987 exhaustiveness: speedup checking 3x-5x
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-driver/src/lib.rs
  compiler/hash-exhaustiveness/src/construct.rs
  compiler/hash-exhaustiveness/src/deconstruct.rs
  compiler/hash-exhaustiveness/src/fields.rs
  compiler/hash-exhaustiveness/src/lib.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-exhaustiveness/src/matrix.rs
  compiler/hash-exhaustiveness/src/range.rs
  compiler/hash-exhaustiveness/src/stack.rs
  compiler/hash-exhaustiveness/src/storage.rs
  compiler/hash-exhaustiveness/src/usefulness.rs
  compiler/hash-exhaustiveness/src/wildcard.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/src/interface.rs
  compiler/hash-semantics/src/env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/tc_env_impl.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-utils/src/timing.rs
Labels: performance

#989 fix improper handling of EOFs in lexer
  compiler/hash-lexer/src/lib.rs
Labels: bug, parser

#992 implement repeat expressions
  compiler/hash-ast-utils/src/pretty/mod.rs
  compiler/hash-ast-utils/src/tree.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/mod.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-driver/src/driver.rs
  compiler/hash-driver/src/lib.rs
  compiler/hash-exhaustiveness/src/wildcard.rs
  compiler/hash-ir-utils/src/lib.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-tir/src/intrinsics/definitions.rs
  compiler/hash-tir/src/tir/data.rs
  compiler/hash-tir/src/tir/lits.rs
  compiler/hash-tir/src/tir/terms/arrays.rs
  compiler/hash-tir/src/visitor.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash/src/main.rs
  tests/cases/codegen/hello_world.hash
  tests/cases/codegen/hello_world.stdout
  tests/cases/codegen/repeated_bytes.hash
  tests/cases/codegen/repeated_bytes.stdout
  tests/cases/lowering/arrays.stdout
  tests/cases/lowering/indexing.stdout
  tests/cases/semantics/entry_point/duplicate_entry_point.hash
  tests/cases/semantics/entry_point/duplicate_entry_point.stderr
  tests/cases/semantics/entry_point/entry_point.hash
  tests/cases/semantics/entry_point/entry_point.stderr
  tests/cases/semantics/entry_point/missing_entry_point.hash
  tests/cases/semantics/entry_point/missing_entry_point.stderr
  tests/cases/semantics/entry_point/named_entry_point.hash
  tests/lib.rs
  tests/runner.rs
  tests/testing-internal/src/metadata.rs
Labels: language

#1004 lexer: better handling of character and byte literals
  Cargo.lock
  compiler/hash-driver/src/driver.rs
  compiler/hash-lexer/src/error.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/name.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-reporting/Cargo.toml
  compiler/hash-reporting/src/lib.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-source/src/location.rs
  tests/cases/parser/literals/byte_literals/combining_marks.hash
  tests/cases/parser/literals/byte_literals/combining_marks.stderr
  tests/cases/parser/literals/byte_literals/non_ascii_byte_literals.hash
  tests/cases/parser/literals/byte_literals/non_ascii_byte_literals.stderr
  tests/cases/parser/literals/characters/combining_marks.hash
  tests/cases/parser/literals/characters/combining_marks.stderr
  tests/cases/parser/literals/characters/multi_error_char.stderr
  tests/cases/reporting/pre_code_marks.hash
  tests/cases/reporting/pre_code_marks.stderr
Labels: error-reporting, parser
