Repository hash-org/hashc, pull requests merged in 2023-10, with the labels that each got.

#1008 tc: Add some documentation to module items (Part 1)
  compiler/hash-typecheck/src/env.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/operations/access.rs
  compiler/hash-typecheck/src/operations/args.rs
  compiler/hash-typecheck/src/operations/arrays.rs
  compiler/hash-typecheck/src/operations/blocks.rs
  compiler/hash-typecheck/src/operations/calls.rs
  compiler/hash-typecheck/src/operations/casting.rs
  compiler/hash-typecheck/src/operations/commands.rs
  compiler/hash-typecheck/src/operations/data.rs
  compiler/hash-typecheck/src/operations/fns.rs
  compiler/hash-typecheck/src/operations/holes.rs
  compiler/hash-typecheck/src/operations/intrinsics.rs
  compiler/hash-typecheck/src/operations/lits.rs
  compiler/hash-typecheck/src/operations/matching.rs
  compiler/hash-typecheck/src/operations/mods.rs
  compiler/hash-typecheck/src/operations/params.rs
  compiler/hash-typecheck/src/operations/pats.rs
  compiler/hash-typecheck/src/operations/range.rs
  compiler/hash-typecheck/src/operations/refs.rs
  compiler/hash-typecheck/src/operations/safety.rs
  compiler/hash-typecheck/src/operations/terms.rs
  compiler/hash-typecheck/src/operations/tuples.rs
  compiler/hash-typecheck/src/operations/ty_of.rs
  compiler/hash-typecheck/src/operations/universe.rs
  compiler/hash-typecheck/src/operations/vars.rs
  compiler/hash-typecheck/src/options/mod.rs
  compiler/hash-typecheck/src/options/normalisation.rs
  compiler/hash-typecheck/src/options/unification.rs
  compiler/hash-typecheck/src/tc.rs
  compiler/hash-typecheck/src/traits.rs
  compiler/hash-typecheck/src/utils/cte.rs
  compiler/hash-typecheck/src/utils/dumping.rs
  compiler/hash-typecheck/src/utils/entry_point.rs
  compiler/hash-typecheck/src/utils/exhaustiveness.rs
  compiler/hash-typecheck/src/utils/intrinsic_abilities.rs
  compiler/hash-typecheck/src/utils/matching.rs
  compiler/hash-typecheck/src/utils/mod.rs
  compiler/hash-typecheck/src/utils/normalisation.rs
  compiler/hash-typecheck/src/utils/purity.rs
  compiler/hash-typecheck/src/utils/substitution.rs
  compiler/hash-typecheck/src/utils/unification.rs
Labels: documentation

#1012 ir: Make projections local to a `Body`
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/mod.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-ir-utils/src/graphviz.rs
  compiler/hash-ir-utils/src/lib.rs
  compiler/hash-ir-utils/src/pretty.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-storage/src/store/sequence/local.rs
  compiler/hash-storage/src/store/sequence/mod.rs
  compiler/hash-storage/src/store/sequence/shared.rs
  compiler/hash-tir/src/stores.rs
  compiler/hash-tir/src/tir/args.rs
Labels: lowering

#1021 ast: use `AstNodes<Expr>` for `mod` def contents
  compiler/hash-ast-utils/src/pretty/mod.rs
  compiler/hash-ast-utils/src/tree.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-untyped-semantics/src/analysis/block.rs
  compiler/hash-untyped-semantics/src/visitor.rs
Labels: ast

#1022 ast: make `Array` and `Tuple` expressions rather than `Lit`s
  compiler/hash-ast-utils/src/pretty/mod.rs
  compiler/hash-ast-utils/src/tree.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-parser/src/diagnostics/error.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/cases/parser/literals/missing_value_in_tuple_lit.hash
  tests/cases/parser/literals/missing_value_in_tuple_lit.stderr
  tests/cases/parser/literals/tuple_literals.hash
  tests/cases/parser/misc/issue_223.hash
  tests/cases/parser/misc/issue_223.stderr
  tests/cases/parser/token_macros/macrotastic.hash
  tests/cases/parser/types/incomplete_tuple_literal_type_annotation.hash
  tests/cases/parser/types/incomplete_tuple_literal_type_annotation.stderr
  tests/cases/typecheck/primitives/tuples.hash
  tests/cases/typecheck/property_access/tuple_access.hash
Labels: ast

#1019 utils: Add a context module that uses de-Brujin levels for constant-time indexing
  compiler/hash-utils/src/lib.rs
  compiler/hash-utils/src/scoping/mod.rs
Labels: semantic-analysis

#1031 reporting: fix out of bounds bug for reporting lines at the end of source
  compiler/hash-source/src/location.rs
Labels: error-reporting

#1032 storage: shrink direct sequence element ids from `16bytes` to `12bytes`
  Cargo.lock
  compiler/hash-ast-expand/src/attr.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-attrs/src/attr.rs
  compiler/hash-exhaustiveness/src/construct.rs
  compiler/hash-exhaustiveness/src/deconstruct.rs
  compiler/hash-exhaustiveness/src/fields.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/Cargo.toml
  compiler/hash-layout/src/write.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-storage/src/store/sequence/mod.rs
  compiler/hash-storage/src/store/statics.rs
  compiler/hash-tir/src/stores.rs
  compiler/hash-tir/src/tir/args.rs
  compiler/hash-tir/src/tir/params/mod.rs
  compiler/hash-tir/src/tir/params/utils.rs
  compiler/hash-tir/src/visitor.rs
  compiler/hash-utils/src/lib.rs
Labels: performance, mem-use
