Repository hash-org/hashc, pull requests merged in 2023-03, with the labels that each got.

#809 Fix bug when unifying reference types
  compiler/hash-typecheck/src/unification.rs
Labels: bug, typechecking

#811 Properly integrate the new semantic analysis with the compiler pipeline
  compiler/hash-interactive/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/old/mod.rs
  compiler/hash-semantics/src/passes/ast_utils.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/mod.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-tir/src/atom_info.rs
  compiler/hash-tir/src/directives.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-untyped-semantics/src/lib.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  compiler/hash-utils/src/store.rs
  tests/runner.rs
  tests/testing-internal/src/metadata.rs
Labels: typechecking

#812 Store entry point in semantic env
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-source/src/entry_point.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
Labels: typechecking

#813 Fix some issues with match bindings
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-tir/src/environment/context.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  stdlib/prelude.hash
Labels: typechecking

#814 Add accessors for context binding types and values
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/context.rs
Labels: typechecking

#815 lower+codegen: fix many issues and get `#foreign` items to work
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/misc.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/traits/ty.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/mod.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-layout/src/write.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-tir/src/directives.rs
  stdlib/prelude.hash
Labels: lowering, codegen

#817 lower+codegen: implement casting operations for primitive types
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/traits/builder.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-ir/src/cast.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-tir/src/fns.rs
  stdlib/prelude.hash
Labels: lowering, codegen

#818 Fix some panics during inference
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#819 lower+ir: fix issue with fn scoping args and add `Live` and `Dead` statement variants
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/statement.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/ty/mod.rs
Labels: lowering

#820 Fix inference of constructor patterns
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-typecheck/src/inference.rs
Labels: bug

#821 codegen: fix handling of string and slice types, implement `transmute()` intrinsic
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/debug_info.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-target/src/abi.rs
  stdlib/prelude.hash
Labels: codegen

#822 Linker: implement `Mold` and `Msvc` linkers
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-link/src/linker/gcc.rs
  compiler/hash-link/src/linker/lld.rs
  compiler/hash-link/src/linker/mod.rs
  compiler/hash-link/src/linker/mold.rs
  compiler/hash-link/src/linker/msvc.rs
  compiler/hash-link/src/platform/mod.rs
  stdlib/prelude.hash
Labels: codegen, linker

#823 core: collect timings from stages
  Cargo.lock
  compiler/hash-backend/src/lib.rs
  compiler/hash-codegen-llvm/Cargo.toml
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/basic_blocks.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/optimise.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-lower/src/optimise/simplify.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/interface.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-semantics/Cargo.toml
  compiler/hash-semantics/src/old/exhaustiveness/construct.rs
  compiler/hash-semantics/src/old/exhaustiveness/deconstruct.rs
  compiler/hash-semantics/src/old/exhaustiveness/lower.rs
  compiler/hash-semantics/src/old/exhaustiveness/stack.rs
  compiler/hash-semantics/src/old/exhaustiveness/wildcard.rs
  compiler/hash-semantics/src/old/mod.rs
  compiler/hash-semantics/src/old/storage/cache.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-session/Cargo.toml
  compiler/hash-session/src/lib.rs
  compiler/hash-tir/Cargo.toml
  compiler/hash-tir/src/environment/context.rs
  compiler/hash-tir/src/old/location.rs
  compiler/hash-tir/src/sub.rs
  compiler/hash-tir/src/utils/data.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-utils/src/lib.rs
  compiler/hash-utils/src/timing.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/logger.rs
  compiler/hash/src/main.rs
Labels: core

#827 Support imports during resolution
  compiler/hash-lower/src/lib.rs
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/environment/analysis_progress.rs
  compiler/hash-semantics/src/environment/mod.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/ops/bootstrap.rs
  compiler/hash-semantics/src/ops/common.rs
  compiler/hash-semantics/src/passes/ast_utils.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/mod.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/mod.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-tir/src/ast_info.rs
  compiler/hash-tir/src/environment/source_info.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-typecheck/src/inference.rs
Labels: typechecking

#829 Add proper inference support for return terms
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#839 Implement monomorphisation of terms
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  compiler/hash-untyped-semantics/src/visitor.rs
Labels: typechecking

#842 lower+codegen: tackle some todos and properly support slices
  Cargo.lock
  compiler/hash-ast/src/tree.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/traits/abi.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lang_items.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lexer/Cargo.toml
  compiler/hash-lexer/src/lib.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/optimise.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/ctx.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-parser/Cargo.toml
  compiler/hash-parser/src/lib.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-target/src/primitives.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/old/storage.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  stdlib/prelude.hash
Labels: lowering, codegen

#843 stdlib: add integer printing
  .cargo/config.toml
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-lower/src/build/category.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  stdlib/.gitignore
  stdlib/io.hash
  stdlib/iter.hash
  stdlib/list.hash
  stdlib/net/http.hash
  stdlib/net/sub/domain.hash
  stdlib/num.hash
  stdlib/prelude.hash
  stdlib/printing.hash
  stdlib/string.hash
Labels: standard-library

#844 Simplify context bindings
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-tir/src/ast_info.rs
  compiler/hash-tir/src/control.rs
  compiler/hash-tir/src/environment/context.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/stack.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#845 stdlib(fmt): add float printing function
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-typecheck/src/inference.rs
  stdlib/math.hash
  stdlib/printing.hash
Labels: standard-library

#846 lower+codegen fixes
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-ir/src/cast.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-typecheck/src/normalisation.rs
  stdlib/prelude.hash
Labels: lowering, codegen

#849 exe mode
  compiler/hash-link/src/command.rs
  compiler/hash-link/src/error.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-link/src/linker/mod.rs
  compiler/hash-link/src/platform/mod.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/interface.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-target/src/link.rs
  compiler/hash-target/src/targets/mod.rs
  compiler/hash-target/src/targets/windows_msvc_base.rs
  compiler/hash-target/src/targets/x86_64_pc_windows_msvc.rs
  compiler/hash/src/main.rs
  tests/testing-internal/src/metadata.rs
Labels: core, linker

#848 Refactor inference, add dependent pattern matching and definitions, optional entry point
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-parser/src/parser/definitions.rs
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/old/traverse/visitor.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/data.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  stdlib/eq.hash
  stdlib/prelude.hash
Labels: typechecking

#850 compiler+codegen: fix several issues
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash/src/main.rs
  stdlib/prelude.hash
  stdlib/printing.hash
Labels: core, codegen

#851 tc: fix some introduced problems with inference
  compiler/hash-typecheck/src/inference.rs
Labels: bug

#852 codegen: fix issue with function name symbol mangling
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/symbols/mangle.rs
  compiler/hash-lower/src/lower_ty.rs
Labels: codegen

#853 tc: fix perf regression in inference due to context substitutions
  compiler/hash-typecheck/src/inference.rs
  stdlib/prelude.hash
Labels: typechecking, performance

#854 codegen: cleanup interface and fix issues
  Cargo.lock
  compiler/hash-abi/src/lib.rs
  compiler/hash-codegen-bytecode/Cargo.toml
  compiler/hash-codegen-llvm/Cargo.toml
  compiler/hash-codegen-llvm/src/ctx.rs
  compiler/hash-codegen-llvm/src/fmt.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/misc.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/constants.rs
  compiler/hash-codegen-llvm/src/translation/debug_info.rs
  compiler/hash-codegen-llvm/src/translation/declare.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/layouts.rs
  compiler/hash-codegen-llvm/src/translation/metadata.rs
  compiler/hash-codegen-llvm/src/translation/misc.rs
  compiler/hash-codegen-llvm/src/translation/mod.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/backend.rs
  compiler/hash-codegen/src/lib.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/mod.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/traits/abi.rs
  compiler/hash-codegen/src/traits/builder.rs
  compiler/hash-codegen/src/traits/ctx.rs
  compiler/hash-codegen/src/traits/debug.rs
  compiler/hash-codegen/src/traits/layout.rs
  compiler/hash-codegen/src/traits/mod.rs
  compiler/hash-codegen/src/traits/target.rs
  compiler/hash-codegen/src/traits/ty.rs
  compiler/hash-ir/src/traversal.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-lower/src/optimise/simplify_graph.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  compiler/hash-utils/src/graph/dominators.rs
  compiler/hash/src/main.rs
Labels: codegen

#857 Remove some old comments, fix a bug with block evaluation
  compiler/hash-tir/src/mods.rs
  compiler/hash-typecheck/src/normalisation.rs
  stdlib/prelude.hash
Labels: typechecking

#859 lower: fix bug in local elimination pass
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-lower/src/optimise/simplify_graph.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-target/src/targets/windows_msvc_base.rs
  compiler/hash/src/logger.rs
Labels: lowering

#860 Quickfix a problem where pat bind types are not inferred
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/substitution.rs
Labels: bug
