Repository hash-org/hashc, pull requests merged in 2023-07, with the labels that each got.

#882 Implement `fmt::Display` for TIR structures without requiring Env
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/diagnostics/mod.rs
  compiler/hash-semantics/src/diagnostics/panic.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-tir/src/access.rs
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/arrays.rs
  compiler/hash-tir/src/casting.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-tir/src/control.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/defs.rs
  compiler/hash-tir/src/directives.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/holes.rs
  compiler/hash-tir/src/lits.rs
  compiler/hash-tir/src/locations.rs
  compiler/hash-tir/src/mods.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/refs.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/sub.rs
  compiler/hash-tir/src/symbols.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tuples.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-tir/src/utils/stack.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/params.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  compiler/hash-utils/src/store.rs
Labels: typechecking

#892 tir: Replace some functions in `common.rs` using `Env` by static functions using static stores
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-semantics/src/ops/bootstrap.rs
  compiler/hash-semantics/src/passes/ast_utils.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/discovery/mod.rs
  compiler/hash-semantics/src/passes/discovery/params.rs
  compiler/hash-semantics/src/passes/discovery/visitor.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-tir/src/holes.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/problems.rs
  compiler/hash-tir/src/symbols.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tys.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/data.rs
  compiler/hash-tir/src/utils/mod.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/holes.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  compiler/hash-utils/src/store.rs
Labels: typechecking

#887 Re-add exhaustiveness into compiler pipeline
  Cargo.lock
  compiler/hash-exhaustiveness/Cargo.toml
  compiler/hash-exhaustiveness/src/constant.rs
  compiler/hash-exhaustiveness/src/construct.rs
  compiler/hash-exhaustiveness/src/deconstruct.rs
  compiler/hash-exhaustiveness/src/diagnostics.rs
  compiler/hash-exhaustiveness/src/exhaustiveness.rs
  compiler/hash-exhaustiveness/src/fields.rs
  compiler/hash-exhaustiveness/src/lib.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-exhaustiveness/src/matrix.rs
  compiler/hash-exhaustiveness/src/mod.rs
  compiler/hash-exhaustiveness/src/range.rs
  compiler/hash-exhaustiveness/src/stack.rs
  compiler/hash-exhaustiveness/src/storage.rs
  compiler/hash-exhaustiveness/src/usefulness.rs
  compiler/hash-exhaustiveness/src/wildcard.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/const_range.rs
  compiler/hash-semantics/Cargo.toml
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/diagnostics/mod.rs
  compiler/hash-semantics/src/diagnostics/warning.rs
  compiler/hash-semantics/src/environment/sem_env.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-tir/src/control.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/lits.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/symbols.rs
  compiler/hash-tir/src/utils/params.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  tests/cases/exhaustiveness/enums.hash
  tests/cases/exhaustiveness/missing_enums.hash
  tests/cases/exhaustiveness/missing_enums.stderr
  tests/cases/exhaustiveness/non-exhaustive-constructor-field.hash
  tests/cases/exhaustiveness/non-exhaustive-constructor-field.stderr
  tests/cases/exhaustiveness/non-exhaustive-decl.hash
  tests/cases/exhaustiveness/non-exhaustive-decl.stderr
  tests/cases/exhaustiveness/overlapping_range_ends.hash
  tests/cases/exhaustiveness/overlapping_range_ends.stderr
  tests/cases/exhaustiveness/simple_unreachable_pats.hash
  tests/cases/exhaustiveness/simple_unreachable_pats.stderr
  tests/cases/exhaustiveness/tuples.hash
  tests/disabled-cases/exhaustiveness/non-exhaustive-decl.stderr
  tests/disabled-cases/exhaustiveness/simple_unreachable_pats.stderr
Labels: typechecking, pattern-matching

#895 tests: re-enable entry point tests
  compiler/hash-semantics/src/diagnostics/error.rs
  tests/cases/codegen/missing_entry_point.hash
  tests/cases/codegen/named_entry_point.hash
Labels: tests, semantic-analysis

#897 ir+lower: remove old TIR `stores()` API and migrate to new methods
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-tir/src/symbols.rs
  tests/cases/lowering/early_returns.stdout
Labels: lowering

#894 support open ranges in patterns, i.e. `4..`, `..<5` `..`, etc
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-exhaustiveness/src/lower.rs
  compiler/hash-exhaustiveness/src/range.rs
  compiler/hash-fmt/src/lib.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/const_range.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/utils/mod.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-untyped-semantics/src/diagnostics/error.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/cases/exhaustiveness/open_ranges.hash
  tests/cases/exhaustiveness/open_ranges.stderr
  tests/cases/parser/patterns/incomplere_exclusive_range_pat.hash
  tests/cases/parser/patterns/incomplere_exclusive_range_pat.stderr
  tests/cases/parser/patterns/incomplete_range_pat.hash
  tests/cases/parser/patterns/incomplete_range_pat.stderr
  tests/cases/semantics/incomplete_range_ending.hash
  tests/cases/semantics/incomplete_range_ending.stderr
Labels: language

#904 Make IR as static as possible
  Cargo.lock
  compiler/hash-codegen-llvm/src/ctx.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/constants.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/layouts.rs
  compiler/hash-codegen-llvm/src/translation/misc.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/symbols/mangle.rs
  compiler/hash-codegen/src/traits/mod.rs
  compiler/hash-codegen/src/traits/ty.rs
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/cast.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/visitor.rs
  compiler/hash-ir/src/write/graphviz.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-ir/src/write/pretty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-layout/src/write.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/const_range.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/matches/optimise.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/temp.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/ctx.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-storage/src/store/mod.rs
  compiler/hash-tir/src/environment/stores.rs
Labels: core, lowering, codegen

#906 tir: use FxBuildHasher for scope hashing
  compiler/hash-tir/src/context.rs
Labels: performance

#905 Make layouts static
  compiler/hash-abi/src/lib.rs
  compiler/hash-codegen-llvm/src/ctx.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/layouts.rs
  compiler/hash-codegen-llvm/src/translation/mod.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/mod.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/statement.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/lower/utils.rs
  compiler/hash-codegen/src/traits/builder.rs
  compiler/hash-codegen/src/traits/layout.rs
  compiler/hash-codegen/src/traits/mod.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-layout/src/write.rs
  compiler/hash-lower/src/ctx.rs
Labels: core

#907 spanless ast
  Cargo.lock
  compiler/hash-ast/Cargo.toml
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/lib.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-tir/Cargo.toml
  compiler/hash-tir/src/ast_info.rs
  compiler/hash-tir/src/locations.rs
  compiler/hash-tir/src/problems.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tree-def/src/emit.rs
  compiler/hash-utils/src/lib.rs
Labels: ast

#910 Speedup lowering by 20-25%
  compiler/hash-ir/src/ty.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-utils/src/lib.rs
Labels: lowering

#913 Add some TC tests
  tests/cases/typecheck/enums/adt.hash
  tests/cases/typecheck/enums/basic.hash
  tests/cases/typecheck/enums/indexed.hash
  tests/cases/typecheck/functions/calling.hash
  tests/cases/typecheck/functions/inference.hash
  tests/cases/typecheck/functions/recursion.hash
  tests/cases/typecheck/misc/expr.hash
  tests/cases/typecheck/misc/imperative.hash
  tests/cases/typecheck/misc/monad.hash
  tests/cases/typecheck/misc/nat.hash
  tests/cases/typecheck/primitives/chars.hash
  tests/cases/typecheck/primitives/collections.hash
  tests/cases/typecheck/primitives/integers.hash
  tests/cases/typecheck/primitives/strings.hash
  tests/cases/typecheck/primitives/tuples.hash
  tests/cases/typecheck/property_access/numeric_access_on_struct.hash
  tests/cases/typecheck/property_access/numeric_access_on_struct.stderr
  tests/cases/typecheck/property_access/out_of_bounds_access.hash
  tests/cases/typecheck/property_access/out_of_bounds_access.stderr
  tests/cases/typecheck/property_access/tuple_access.hash
  tests/cases/typecheck/spread_pats/tuple-spread-pats.hash
  tests/cases/typecheck/structs/basic.hash
  tests/cases/typecheck/structs/missing-fields.hash
  tests/cases/typecheck/structs/missing-fields.stderr
  tests/cases/typecheck/structs/pattern-matching.hash
  tests/disabled-cases/typecheck/functions/non-rt-arg.hash
  tests/disabled-cases/typecheck/functions/non-rt-arg.stderr
  tests/disabled-cases/typecheck/functions/non-rt-return.hash
  tests/disabled-cases/typecheck/functions/non-rt-return.stderr
  tests/disabled-cases/typecheck/functions/recursion.hash
  tests/disabled-cases/typecheck/primitives/collections.hash
  tests/disabled-cases/typecheck/property_access/numeric_access_on_struct.stderr
  tests/disabled-cases/typecheck/property_access/out_of_bounds_access.stderr
  tests/disabled-cases/typecheck/structs/malformed-field-types.hash
  tests/disabled-cases/typecheck/structs/malformed-field-types.stderr
  tests/disabled-cases/typecheck/structs/missing-fields.stderr
  tests/disabled-cases/typecheck/traits/compound_errors.hash
  tests/disabled-cases/typecheck/traits/compound_errors.stderr
  tests/disabled-cases/typecheck/traits/unspecified_member.hash
  tests/disabled-cases/typecheck/traits/unspecified_member.stderr
Labels: tests, typechecking
