Repository hash-org/hashc, pull requests merged in 2023-02, with the labels that each got.

#756 Remove DefParams/DefArgs/DefPatArgs in favour of the simple versions
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-semantics/src/new/diagnostics/error.rs
  compiler/hash-semantics/src/new/passes/discovery/params.rs
  compiler/hash-semantics/src/new/passes/discovery/visitor.rs
  compiler/hash-semantics/src/new/passes/resolution/params.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/pats.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-tir/src/new/data.rs
  compiler/hash-tir/src/new/defs.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/environment/stores.rs
  compiler/hash-tir/src/new/locations.rs
  compiler/hash-tir/src/new/params.rs
  compiler/hash-tir/src/new/pats.rs
  compiler/hash-tir/src/new/tuples.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-tir/src/new/utils/data.rs
  compiler/hash-tir/src/new/utils/defs.rs
  compiler/hash-tir/src/new/utils/params.rs
  compiler/hash-tir/src/new/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#759 Resolve dependent tuple members
  compiler/hash-semantics/src/new/passes/discovery/defs.rs
  compiler/hash-semantics/src/new/passes/discovery/visitor.rs
  compiler/hash-semantics/src/new/passes/resolution/defs.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/params.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/scoping.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#760 Add an equality judgement
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-typecheck/src/inference.rs
Labels: typechecking

#761 pipeline+codegen= ❤️ | integrate LLVM backend with the pipeline
  Cargo.lock
  compiler/hash-abi/Cargo.toml
  compiler/hash-backend/Cargo.toml
  compiler/hash-backend/src/lib.rs
  compiler/hash-codegen-llvm/src/context.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/misc.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/constants.rs
  compiler/hash-codegen-llvm/src/translation/debug_info.rs
  compiler/hash-codegen-llvm/src/translation/declare.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/layouts.rs
  compiler/hash-codegen-llvm/src/translation/metadata.rs
  compiler/hash-codegen-llvm/src/translation/misc.rs
  compiler/hash-codegen-llvm/src/translation/mod.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/Cargo.toml
  compiler/hash-codegen/src/backend/mod.rs
  compiler/hash-codegen/src/lib.rs
  compiler/hash-codegen/src/lower/block.rs
  compiler/hash-codegen/src/lower/debug_info.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/mod.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/statement.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/lower/utils.rs
  compiler/hash-codegen/src/traits/builder.rs
  compiler/hash-ir/Cargo.toml
  compiler/hash-ir/src/basic_blocks.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/Cargo.toml
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/cfg.rs
  compiler/hash-lower/src/optimise/cleanup_locals.rs
  compiler/hash-lower/src/optimise/simplify.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/error.rs
  compiler/hash-pipeline/src/fs.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/lib.rs
  compiler/hash-target/build.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-utils/src/store.rs
  compiler/hash/src/main.rs
  tests/runner.rs
Labels: codegen

#762 Allow definitions in runtime blocks, and partially implement normalisation
  compiler/hash-semantics/src/new/diagnostics/error.rs
  compiler/hash-semantics/src/new/passes/discovery/defs.rs
  compiler/hash-semantics/src/new/passes/discovery/visitor.rs
  compiler/hash-semantics/src/new/passes/resolution/defs.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/params.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/pats.rs
  compiler/hash-semantics/src/new/passes/resolution/scoping.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/scopes.rs
  compiler/hash-tir/src/new/terms.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-tir/src/new/utils/stack.rs
  compiler/hash-tir/src/new/utils/traversing.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/unification.rs
  compiler/hash-utils/src/store.rs
Labels: typechecking

#764 codegen: some fixes with code generation and layout info
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/metadata.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/block.rs
  compiler/hash-codegen/src/lower/mod.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-ir/src/basic_blocks.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/mod.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-utils/src/graph/dominators.rs
  compiler/hash-utils/src/graph/mod.rs
  compiler/hash-utils/src/graph/tests/mod.rs
  compiler/hash-utils/src/graph/visit.rs
  compiler/hash-utils/src/lib.rs
  compiler/hash/src/main.rs
Labels: bug, landmark, codegen

#766 codegen: several fixes
  Cargo.lock
  compiler/hash-ast-expand/src/visitor.rs
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-backend/src/lib.rs
  compiler/hash-codegen-llvm/Cargo.toml
  compiler/hash-codegen-llvm/src/context.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen-llvm/src/translation/ty.rs
  compiler/hash-codegen/src/lower/locals.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/cases/semantics/directives/unknown_directive.stderr
Labels: bug, codegen

#765 Implement normalisation of TIR terms
  compiler/hash-semantics/src/new/passes/inference/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/pats.rs
  compiler/hash-tir/src/new/control.rs
  compiler/hash-tir/src/new/lits.rs
  compiler/hash-tir/src/new/pats.rs
  compiler/hash-tir/src/new/scopes.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-tir/src/new/utils/traversing.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#770 Fix some normalisation bugs
  compiler/hash-semantics/src/new/passes/discovery/defs.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/pats.rs
  compiler/hash-semantics/src/new/passes/resolution/scoping.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/scopes.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-tir/src/new/utils/stack.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
Labels: typechecking

#771 codegen: emit a wrapper for entry point
  Cargo.lock
  compiler/hash-backend/src/error.rs
  compiler/hash-backend/src/lib.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen-llvm/src/translation/misc.rs
  compiler/hash-codegen/src/backend/mod.rs
  compiler/hash-codegen/src/lower/abi.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/symbols/mangle.rs
  compiler/hash-codegen/src/symbols/mod.rs
  compiler/hash-codegen/src/traits/misc.rs
  compiler/hash-codegen/src/traits/ty.rs
  compiler/hash-error-codes/src/error_codes.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-reporting/src/render.rs
  compiler/hash-reporting/src/report.rs
  compiler/hash-semantics/Cargo.toml
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/storage/mod.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-source/src/entry_point.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-tir/src/location.rs
  compiler/hash-tir/src/storage.rs
  compiler/hash-untyped-semantics/src/visitor.rs
  tests/.gitignore
  tests/cases/codegen/duplicate_entry_point.hash
  tests/cases/codegen/duplicate_entry_point.stderr
  tests/cases/codegen/missing_entry_point.hash
  tests/cases/codegen/missing_entry_point.stderr
  tests/cases/codegen/named_entry_point.hash
  tests/cases/semantics/directives/entry_point.hash
  tests/cases/semantics/directives/entry_point.stderr
  tests/runner.rs
  tests/testing-internal/src/metadata.rs
Labels: codegen

#773 link: Initial setup of linking wrappers for the compiler
  Cargo.lock
  Cargo.toml
  compiler/hash-ast/src/tree.rs
  compiler/hash-backend/Cargo.toml
  compiler/hash-link/Cargo.toml
  compiler/hash-link/src/gcc.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-link/src/lld.rs
  compiler/hash-link/src/mold.rs
  compiler/hash-link/src/msvc.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/mod.rs
  compiler/hash-semantics/Cargo.toml
  compiler/hash-semantics/src/diagnostics/error.rs
  compiler/hash-semantics/src/exhaustiveness/deconstruct.rs
  compiler/hash-semantics/src/exhaustiveness/fields.rs
  compiler/hash-semantics/src/exhaustiveness/lower.rs
  compiler/hash-semantics/src/exhaustiveness/usefulness.rs
  compiler/hash-semantics/src/new/passes/discovery/visitor.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-semantics/src/ops/exhaustiveness.rs
  compiler/hash-semantics/src/ops/params.rs
  compiler/hash-semantics/src/ops/pats.rs
  compiler/hash-semantics/src/ops/scope.rs
  compiler/hash-semantics/src/ops/simplify.rs
  compiler/hash-semantics/src/ops/typing.rs
  compiler/hash-semantics/src/ops/validate.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/lib.rs
  tests/cases/lowering/aggregates.hash
  tests/cases/lowering/aggregates.stdout
  tests/cases/lowering/functions.stdout
  tests/cases/lowering/indexing.hash
  tests/cases/lowering/indexing.stdout
  tests/cases/lowering/loops.hash
  tests/cases/lowering/loops.stdout
  tests/cases/lowering/match_ranges.hash
  tests/cases/lowering/match_ranges.stdout
  tests/cases/lowering/nested_loops.hash
  tests/cases/lowering/operators.hash
  tests/cases/lowering/simple_match.hash
  tests/cases/lowering/simple_match.stdout
  tests/cases/parser/misc/issue_557.hash
  tests/cases/parser/misc/strip_shebangs.hash
  tests/testing-internal/src/metadata.rs
  tests/testing-macros/src/lib.rs
Labels: bug, parser, lowering, codegen

#776 Fix some inference bugs and implement constructor type argument inference
  compiler/hash-semantics/src/new/passes/inference/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/params.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/scoping.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-tir/src/new/environment/context.rs
  compiler/hash-tir/src/new/sub.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/context.rs
  compiler/hash-tir/src/new/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#780 Linker: finish implementing the linker and cleanup cmdargs
  Cargo.lock
  compiler/hash-codegen-llvm/src/error.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/misc.rs
  compiler/hash-codegen-llvm/src/translation/abi.rs
  compiler/hash-codegen/src/symbols/mangle.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-link/Cargo.toml
  compiler/hash-link/src/command.rs
  compiler/hash-link/src/error.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-link/src/linker/gcc.rs
  compiler/hash-link/src/linker/lld.rs
  compiler/hash-link/src/linker/mod.rs
  compiler/hash-link/src/linker/mold.rs
  compiler/hash-link/src/linker/msvc.rs
  compiler/hash-link/src/platform/apple.rs
  compiler/hash-link/src/platform/mod.rs
  compiler/hash-link/src/platform/windows.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-source/src/attributes.rs
  compiler/hash-source/src/identifier.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-target/src/link.rs
  compiler/hash-target/src/targets/apple_base.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/lib.rs
Labels: landmark, codegen, linker

#781 Implement implicit argument inference for function calls and constructors
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-semantics/src/new/passes/inference/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/data.rs
  compiler/hash-tir/src/new/utils/params.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#782 codegen+layout: fix issue with string literals not being dealt with properly.
  compiler/hash-codegen-llvm/src/translation/builder.rs
  compiler/hash-codegen/src/lower/operands.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-codegen/src/traits/builder.rs
  compiler/hash-ir/src/mod.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-ir/src/write/mod.rs
  compiler/hash-layout/src/write.rs
Labels: bug, codegen

#783 language: remove `map` and `set` syntax from the language for now
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  compiler/hash-token/src/keyword.rs
  tests/cases/parser/literals/map_literals.hash
  tests/cases/parser/literals/set_literals.hash
  tests/cases/parser/types/enum_with_ty_params.hash
  tests/cases/parser/types/struct_with_ty_params.hash
Labels: language

#784 language: rename list language items to arrays and add sized array types
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/origin.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-codegen-llvm/src/misc.rs
  compiler/hash-codegen/src/backend/mod.rs
  compiler/hash-codegen/src/lower/block.rs
  compiler/hash-codegen/src/lower/place.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-layout/src/write.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/candidate.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-semantics/src/exhaustiveness/construct.rs
  compiler/hash-semantics/src/exhaustiveness/deconstruct.rs
  compiler/hash-semantics/src/exhaustiveness/fields.rs
  compiler/hash-semantics/src/exhaustiveness/list.rs
  compiler/hash-semantics/src/exhaustiveness/lower.rs
  compiler/hash-semantics/src/exhaustiveness/mod.rs
  compiler/hash-semantics/src/exhaustiveness/wildcard.rs
  compiler/hash-semantics/src/new/environment/ast_info.rs
  compiler/hash-semantics/src/new/passes/discovery/defs.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/pats.rs
  compiler/hash-semantics/src/new/passes/resolution/scoping.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-semantics/src/ops/core.rs
  compiler/hash-semantics/src/ops/oracle.rs
  compiler/hash-semantics/src/ops/pats.rs
  compiler/hash-semantics/src/ops/substitute.rs
  compiler/hash-semantics/src/ops/typing.rs
  compiler/hash-semantics/src/storage/sources.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  compiler/hash-tir/src/bootstrap.rs
  compiler/hash-tir/src/builder.rs
  compiler/hash-tir/src/new/data.rs
  compiler/hash-tir/src/new/lits.rs
  compiler/hash-tir/src/new/pats.rs
  compiler/hash-tir/src/new/utils/traversing.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/unification.rs
  tests/cases/lowering/indexing.hash
  tests/cases/semantics/pats/multiple_spread.stderr
  tests/cases/typecheck/enums/basic.hash
  tests/cases/typecheck/primitives/collections.hash
Labels: language

#787 Add better inference for numeric literals and some resolution bug fixes
  compiler/hash-semantics/src/new/diagnostics/error.rs
  compiler/hash-semantics/src/new/passes/ast_utils.rs
  compiler/hash-semantics/src/new/passes/discovery/mod.rs
  compiler/hash-semantics/src/new/passes/discovery/params.rs
  compiler/hash-semantics/src/new/passes/discovery/visitor.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/paths.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-typecheck/src/inference.rs
Labels: typechecking

#788 parser: introduce types in expressions and type literals
  compiler/hash-ast/src/ast.rs
  compiler/hash-ast/src/tree.rs
  compiler/hash-parser/src/diagnostics/warning.rs
  compiler/hash-parser/src/parser/block.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/ty.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-semantics/src/traverse/visitor.rs
  tests/cases/exhaustiveness/overlapping_range_ends.hash
  tests/cases/exhaustiveness/overlapping_range_ends.stderr
  tests/cases/exhaustiveness/simple_unreachable_pats.hash
  tests/cases/exhaustiveness/simple_unreachable_pats.stderr
  tests/cases/exhaustiveness/tuples.hash
  tests/cases/lowering/match_ranges.hash
  tests/cases/lowering/simple_match.hash
  tests/cases/parser/blocks/block_directive.hash
  tests/cases/parser/blocks/nested_match.hash
  tests/cases/parser/blocks/unsafe_blocks.hash
  tests/cases/parser/constructors/compount_pattern_matching_with_structs.hash
  tests/cases/parser/constructors/struct_pattern_matching.hash
  tests/cases/parser/misc/issue_779.hash
  tests/cases/parser/patterns/compound_pattern_matching.hash
  tests/cases/parser/patterns/enum_pat_matching.hash
  tests/cases/parser/patterns/list_patterns_in_match_cases.hash
  tests/cases/parser/patterns/negative_numerics_in_pats.hash
  tests/cases/parser/patterns/pat_match_missing_comma.hash
  tests/cases/parser/patterns/pat_match_missing_comma.stderr
  tests/cases/parser/patterns/pat_match_missing_semi.stderr
  tests/cases/parser/patterns/pattern_matching_literals.hash
  tests/cases/parser/patterns/pattern_matching_with_strings.hash
  tests/cases/parser/patterns/range_pats.hash
  tests/cases/parser/patterns/xor_in_match.hash
  tests/cases/parser/types/exprs_in_tys/disallowed_exprs.hash
  tests/cases/parser/types/exprs_in_tys/disallowed_exprs.stderr
  tests/cases/parser/types/exprs_in_tys/exprs_in_braces.hash
  tests/cases/parser/types/exprs_in_tys/literals.hash
  tests/cases/semantics/pats/multiple_spread.hash
  tests/cases/semantics/pats/multiple_spread.stderr
  tests/cases/typecheck/property_access/tuple_access.hash
  tests/cases/typecheck/structs/pattern-matching.hash
  tests/cases/typecheck/traits/compound_errors.hash
  tests/cases/typecheck/traits/compound_errors.stderr
  tests/cases/typecheck/traits/unspecified_member.hash
  tests/cases/typecheck/traits/unspecified_member.stderr
  tests/runner.rs
Labels: parser, language

#789 source: refactor `IntConstant` to use value slots rather than scalar
  compiler/hash-codegen-llvm/src/translation/constants.rs
  compiler/hash-ir/src/ir.rs
  compiler/hash-lexer/src/lib.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/matches/test.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-parser/src/lib.rs
  compiler/hash-parser/src/parser/expr.rs
  compiler/hash-parser/src/parser/lit.rs
  compiler/hash-parser/src/source.rs
  compiler/hash-semantics/src/exhaustiveness/constant.rs
  compiler/hash-semantics/src/exhaustiveness/lower.rs
  compiler/hash-semantics/src/exhaustiveness/range.rs
  compiler/hash-semantics/src/ops/typing.rs
  compiler/hash-semantics/src/ops/validate.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-source/src/lib.rs
  compiler/hash-target/src/primitives.rs
  compiler/hash-tir/src/new/lits.rs
  compiler/hash-tir/src/terms.rs
Labels: ast, core

#790 Add intrinsics for operators and use them in normalisation
  Cargo.lock
  compiler/hash-ast/src/ast.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-intrinsics/Cargo.toml
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/new/environment/tc_env.rs
  compiler/hash-semantics/src/new/ops/bootstrap.rs
  compiler/hash-semantics/src/new/passes/resolution/exprs.rs
  compiler/hash-semantics/src/new/passes/resolution/mod.rs
  compiler/hash-semantics/src/new/passes/resolution/tys.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-tir/src/new/utils/common.rs
  compiler/hash-tir/src/new/utils/mods.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#791 Add AtomInfo store to store inference of terms to their types
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-semantics/src/new/passes/inference/mod.rs
  compiler/hash-tir/src/new/args.rs
  compiler/hash-tir/src/new/atom_info.rs
  compiler/hash-tir/src/new/environment/stores.rs
  compiler/hash-tir/src/new/fns.rs
  compiler/hash-tir/src/new/mod.rs
  compiler/hash-tir/src/new/utils/mod.rs
  compiler/hash-tir/src/new/utils/mods.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#792 lower: write out logic to convert TIR types into IR types
  Cargo.lock
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen-llvm/src/translation/intrinsics.rs
  compiler/hash-codegen/src/lower/intrinsics.rs
  compiler/hash-codegen/src/lower/rvalue.rs
  compiler/hash-codegen/src/lower/terminator.rs
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-ir/src/intrinsics.rs
  compiler/hash-ir/src/lib.rs
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/optimise.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/discover.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-lower/src/ty/new.rs
  compiler/hash-lower/src/ty/old.rs
  compiler/hash-semantics/src/new/ops/bootstrap.rs
  compiler/hash-session/src/lib.rs
  compiler/hash-target/src/abi.rs
  compiler/hash-tir/src/new/data.rs
  compiler/hash-tir/src/new/fns.rs
  compiler/hash-typecheck/src/inference.rs
Labels: lowering

#793 Add logic to discover all non-pure functions in the sources
  Cargo.lock
  compiler/hash-lower/Cargo.toml
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/new_discover.rs
  compiler/hash-tir/src/new/utils/mods.rs
Labels: lowering

#796 Track directives in the TIR
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-tir/src/directives.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/mod.rs
Labels: typechecking

#797 Fix some issues with normalisation and recursive inference
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/inference/mod.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/atom_info.rs
  compiler/hash-tir/src/utils/common.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#798 Fix bug where locations get unset when adding duplicate entries
  compiler/hash-tir/src/locations.rs
Labels: bug

#799 Do not fmap functions that are intrinsic
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-tir/src/utils/traversing.rs
Labels: bug

#800 Implement typechecking of matches, arrays, indexing, assign terms
  compiler/hash-intrinsics/src/intrinsics.rs
  compiler/hash-intrinsics/src/primitives.rs
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/category.rs
  compiler/hash-lower/src/build/constant.rs
  compiler/hash-lower/src/build/expr.rs
  compiler/hash-lower/src/build/matches/declarations.rs
  compiler/hash-lower/src/build/place.rs
  compiler/hash-lower/src/build/rvalue.rs
  compiler/hash-lower/src/build/ty.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-lower/src/ty/mod.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/access.rs
  compiler/hash-tir/src/arrays.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/lits.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/utils/traversing.rs
  compiler/hash-typecheck/src/errors.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/unification.rs
Labels: typechecking

#803 Fix desugared loops resolution
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
Labels: bug

#804 Implement resolution of assign-op
  compiler/hash-semantics/src/passes/resolution/exprs.rs
Labels: typechecking
