Repository hash-org/hashc, pull requests merged in 2023-06, with the labels that each got.

#863 source: introduce `LineRanges` to represent line ranges of a module source
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  compiler/hash-parser/src/parser/pat.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-semantics/src/diagnostics/panic.rs
  compiler/hash-source/Cargo.toml
  compiler/hash-source/src/lib.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/lib.rs
  compiler/hash-utils/src/range_map.rs
  compiler/hash-utils/src/store.rs
Labels: core

#866 Remove eval_impure_fns flag from normalisation mode
  compiler/hash-semantics/src/passes/evaluation/mod.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
Labels: typechecking

#868 tc: Remove the usage of `Context` in `hash-semantics`
  compiler/hash-intrinsics/src/utils.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/build/utils.rs
  compiler/hash-lower/src/lower_ty.rs
  compiler/hash-semantics/src/passes/mod.rs
  compiler/hash-semantics/src/passes/resolution/defs.rs
  compiler/hash-semantics/src/passes/resolution/exprs.rs
  compiler/hash-semantics/src/passes/resolution/mod.rs
  compiler/hash-semantics/src/passes/resolution/paths.rs
  compiler/hash-semantics/src/passes/resolution/pats.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/environment/context.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
Labels: typechecking

#872 tc: Make TIR stores static and implement convenience methods for IDs
  Cargo.lock
  compiler/hash-tir/Cargo.toml
  compiler/hash-tir/src/args.rs
  compiler/hash-tir/src/data.rs
  compiler/hash-tir/src/environment/env.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/fns.rs
  compiler/hash-tir/src/mods.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/symbols.rs
  compiler/hash-tir/src/terms.rs
  compiler/hash-tir/src/tys.rs
Labels: typechecking

#873 Make stores multithreaded by RwLock and DashMap
  Cargo.lock
  compiler/hash-ast-expand/Cargo.toml
  compiler/hash-backend/Cargo.toml
  compiler/hash-codegen/src/traits/abi.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-ir/src/ty.rs
  compiler/hash-layout/src/compute.rs
  compiler/hash-layout/src/lib.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-reporting/Cargo.toml
  compiler/hash-semantics/Cargo.toml
  compiler/hash-session/Cargo.toml
  compiler/hash-tir/Cargo.toml
  compiler/hash-tir/src/ast_info.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/locations.rs
  compiler/hash-tir/src/mods.rs
  compiler/hash-tir/src/pats.rs
  compiler/hash-tir/src/utils/mods.rs
  compiler/hash-tree-def/Cargo.toml
  compiler/hash-typecheck/Cargo.toml
  compiler/hash-untyped-semantics/Cargo.toml
  compiler/hash-utils/Cargo.toml
  compiler/hash-utils/src/store.rs
  compiler/hash-vm/Cargo.toml
  tests/testing-internal/Cargo.toml
Labels: typechecking

#874 interface: use clap argument parsing for CLI
  Cargo.lock
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/args.rs
  compiler/hash-pipeline/src/error.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-target/src/lib.rs
  compiler/hash-target/src/targets/linux_base.rs
  compiler/hash-target/src/targets/linux_gnu_base.rs
  compiler/hash-target/src/targets/mod.rs
  compiler/hash-target/src/targets/x86_64_unknown_linux_gnu.rs
  compiler/hash-utils/src/tree_writing.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/main.rs
  tests/Cargo.toml
  tests/cases/lowering/aggregates.hash
  tests/cases/lowering/arrays.hash
  tests/cases/lowering/constructor_matches.hash
  tests/cases/lowering/dataless_closures.hash
  tests/cases/lowering/early_returns.hash
  tests/cases/lowering/fn_return.hash
  tests/cases/lowering/functions.hash
  tests/cases/lowering/indexing.hash
  tests/cases/lowering/list_literals.hash
  tests/cases/lowering/loops.hash
  tests/cases/lowering/match_ranges.hash
  tests/cases/lowering/matches_with_guards.hash
  tests/cases/lowering/nested_loops.hash
  tests/cases/lowering/operators.hash
  tests/cases/lowering/polymorphic_fns.hash
  tests/cases/lowering/return_if.hash
  tests/cases/lowering/simple_match.hash
  tests/cases/lowering/string_literals.hash
  tests/cases/lowering/strings_in_matches.hash
  tests/cases/lowering/unreachable_optimisation.hash
  tests/cases/lowering/while_loops.hash
  tests/runner.rs
Labels: interface

#875 tc: Use global stores in environment
  Cargo.lock
  compiler/hash-lower/src/build/block.rs
  compiler/hash-lower/src/build/into.rs
  compiler/hash-lower/src/build/matches/mod.rs
  compiler/hash-lower/src/build/mod.rs
  compiler/hash-lower/src/lib.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-semantics/src/passes/discovery/defs.rs
  compiler/hash-semantics/src/passes/resolution/params.rs
  compiler/hash-semantics/src/passes/resolution/scoping.rs
  compiler/hash-semantics/src/passes/resolution/tys.rs
  compiler/hash-tir/src/ast_info.rs
  compiler/hash-tir/src/context.rs
  compiler/hash-tir/src/environment/env.rs
  compiler/hash-tir/src/environment/mod.rs
  compiler/hash-tir/src/environment/stores.rs
  compiler/hash-tir/src/lib.rs
  compiler/hash-tir/src/params.rs
  compiler/hash-tir/src/scopes.rs
  compiler/hash-tir/src/utils/context.rs
  compiler/hash-tir/src/utils/stack.rs
  compiler/hash-typecheck/src/inference.rs
  compiler/hash-typecheck/src/normalisation.rs
  compiler/hash-typecheck/src/substitution.rs
  compiler/hash-typecheck/src/unification.rs
  tests/Cargo.toml
  tests/testing-macros/src/lib.rs
Labels: typechecking

#878 Introduce `hash_driver` as public facing compiler API
  Cargo.lock
  compiler/hash-backend/src/lib.rs
  compiler/hash-codegen-llvm/src/lib.rs
  compiler/hash-codegen/src/backend.rs
  compiler/hash-driver/Cargo.toml
  compiler/hash-driver/src/driver.rs
  compiler/hash-driver/src/lib.rs
  compiler/hash-interactive/Cargo.toml
  compiler/hash-interactive/build.rs
  compiler/hash-interactive/src/command.rs
  compiler/hash-interactive/src/error.rs
  compiler/hash-interactive/src/lib.rs
  compiler/hash-link/src/lib.rs
  compiler/hash-pipeline/src/error.rs
  compiler/hash-pipeline/src/lib.rs
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-semantics/src/lib.rs
  compiler/hash-untyped-semantics/src/lib.rs
  compiler/hash/Cargo.toml
  compiler/hash/src/main.rs
  tests/Cargo.toml
  tests/runner.rs
Labels: interface

#879 driver: implement `DerefMut` on driver in order to access mutable APIs
  compiler/hash-driver/src/driver.rs
Labels: interface

#881 fmt: begin working on formatting library
  Cargo.lock
  compiler/hash-ast-desugaring/src/lib.rs
  compiler/hash-ast-expand/Cargo.toml
  compiler/hash-ast-expand/src/lib.rs
  compiler/hash-ast-expand/src/visitor.rs
  compiler/hash-fmt/Cargo.toml
  compiler/hash-fmt/src/collection.rs
  compiler/hash-fmt/src/config.rs
  compiler/hash-fmt/src/lib.rs
  compiler/hash-fmt/src/state.rs
  compiler/hash-pipeline/Cargo.toml
  compiler/hash-pipeline/src/settings.rs
  compiler/hash-pipeline/src/workspace.rs
  compiler/hash-source/src/constant.rs
  compiler/hash-token/src/delimiter.rs
  compiler/hash-tree-def/Cargo.toml
  compiler/hash-tree-def/src/definitions.rs
  compiler/hash-utils/src/state.rs
Labels: fmt
